// fund plan <slug> | --all [--json]   and   fund next <slug>
// Resolve the app's pipeline, evaluate every step's done() from files, print the plan, write PLAN.md.

import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { resolvePipeline, makeCtx, evaluate, firstActionable, instructionsOf, nextCommand, readState, isMonitor } from '../pipeline.mjs';

const MARK = '<!-- generated by fund plan; safe to delete -->';
const ICON = { done: '✓', next: '→', human: '☐', blocked: '·', pending: '○' };

export function daysLeft(core, deadline) {
  const t = core.parseDeadline(deadline);
  if (t == null || Number.isNaN(t)) return null;
  return (t - core.now().getTime()) / 86400000;
}

export function dueLabel(core, deadline) {
  const d = daysLeft(core, deadline);
  if (d == null) return String(deadline || 'rolling');
  return `${String(deadline).slice(0, 10)} (${d < 0 ? `${Math.abs(Math.round(d))}d ago` : `${Math.round(d)}d`})`;
}

export async function planFor(slug, { core, tracks, runAI, invoke, flags = {} }) {
  const steps = await resolvePipeline({ slug, core, tracks });
  const ctx = makeCtx({ slug, core, runAI, invoke, tracks, flags });
  const rows = await evaluate(steps, ctx);
  const state = readState(ctx.dir);
  const fm = ctx.app.call.fm;
  const next = firstActionable(rows);
  // A parked Track E app is a monitor, not closed: its pipeline keeps scanning while parked.
  const closed = core.CLOSED.has(fm.status) && !rows.every((r) => r.done) && !(fm.status === 'parked' && isMonitor(steps));
  const lastFail = next && state.steps[next.step.id]?.status === 'failed' ? state.steps[next.step.id].last : '';
  const remainingHuman = rows.filter((r) => !r.done && r.step.kind === 'human').reduce((n, r) => n + (r.step.estimate_h || 0), 0);
  return { slug, ctx, steps, rows, state, fm, next, closed, lastFail, remainingHuman };
}

function command(p) {
  if (p.closed) return `fund status ${p.slug} drafting   # only to reopen (status ${p.fm.status})`;
  return nextCommand(p.slug, p.next, p.ctx);
}

function planJson(p) {
  return {
    slug: p.slug, track: p.fm.track || '', status: p.fm.status || '', deadline: p.fm.deadline || 'rolling',
    next: p.next ? { id: p.next.step.id, kind: p.next.step.kind, title: p.next.step.title, reason: p.next.reason, lastFailure: p.lastFail || undefined } : null,
    command: command(p),
    remainingHumanHours: p.remainingHuman,
    steps: p.rows.map((r) => ({ id: r.step.id, title: r.step.title, kind: r.step.kind, status: r.status, estimate_h: r.step.estimate_h ?? 0, reason: r.reason, blockedBy: r.blockedBy })),
  };
}

function printPlan(core, p) {
  console.log(`\n${p.slug}  ·  track ${p.fm.track || '?'}  ·  ${p.fm.status || 'researching'}  ·  due ${dueLabel(core, p.fm.deadline)}`);
  console.log(`  ${'#'.padStart(2)}  ${'step'.padEnd(20)} ${'kind'.padEnd(6)} ${'status'.padEnd(8)} ${'est'.padStart(5)}  why`);
  p.rows.forEach((r, i) => {
    const why = r.blocked ? `waits for ${r.blockedBy.join(', ')}` : r.reason;
    console.log(`  ${String(i + 1).padStart(2)}  ${ICON[r.status]} ${r.step.id.padEnd(18)} ${r.step.kind.padEnd(6)} ${r.status.padEnd(8)} ${`${r.step.estimate_h ?? 0}h`.padStart(5)}  ${why}`);
  });
  if (p.closed) console.log(`  status ${p.fm.status}: the engine will not run anything.`);
  if (p.lastFail) console.log(`  last run of ${p.next.step.id} failed: ${p.lastFail}`);
  console.log(`  human time left: ${p.remainingHuman.toFixed(2)}h`);
  console.log(`next: ${command(p)}`);
}

export function planMarkdown(core, p) {
  const lines = [
    MARK,
    `# Plan — ${p.fm.program || p.slug}`,
    '',
    `Track ${p.fm.track || '?'} · status ${p.fm.status || 'researching'} · due ${dueLabel(core, p.fm.deadline)} · generated ${new Date().toISOString().slice(0, 16)}Z`,
    '',
    '| # | Step | Kind | Status | Est. | Why |',
    '|---|---|---|---|---|---|',
    ...p.rows.map((r, i) => `| ${i + 1} | ${r.step.id} — ${r.step.title} | ${r.step.kind} | ${r.status} | ${r.step.estimate_h ?? 0}h | ${(r.blocked ? `waits for ${r.blockedBy.join(', ')}` : r.reason).replace(/\|/g, '\\|').replace(/\n/g, ' ')} |`),
    '',
    `**Next:** \`${command(p)}\``,
    '',
  ];
  const human = p.rows.filter((r) => !r.done && r.step.kind === 'human');
  if (human.length) {
    lines.push('## What needs a person', '');
    for (const r of human) lines.push(`- **${r.step.id}** (${r.step.estimate_h ?? 0}h, ${r.status}): ${instructionsOf(r.step, p.ctx, p.slug) || r.step.title}`);
    lines.push('');
  }
  return lines.join('\n');
}

/** Write PLAN.md, never clobbering a track file with the same name on a case-insensitive disk. */
export function writePlanFile(dir, text) {
  const clash = readdirSync(dir).find((f) => f.toLowerCase() === 'plan.md');
  let target = join(dir, clash || 'PLAN.md');
  if (clash && !readFileSync(target, 'utf8').startsWith(MARK)) {
    mkdirSync(join(dir, '.fund'), { recursive: true });
    target = join(dir, '.fund', 'PLAN.md');
  }
  writeFileSync(target, text);
  return target;
}

const plan = {
  name: 'plan',
  help: '<slug> | --all [--json]    every step: done / next / human / blocked, writes PLAN.md',
  booleanFlags: ['all', 'json'],
  async run({ args, flags, core, runAI, tracks, invoke }) {
    const slugs = flags.all ? core.listApps() : args.slice(0, 1);
    if (flags.all && !slugs.length) {
      if (flags.json) { console.log('[]'); return 0; }
      console.log(`No applications in ${core.PATHS.apps}.`);
      console.log('next: fund new <slug> --track <A-E>');
      return 0;
    }
    if (!slugs.length) { console.error('usage: plan <slug> | --all [--json]'); return 2; }
    const plans = [];
    for (const slug of slugs) {
      if (!existsSync(join(core.appDir(slug), 'call.md'))) { console.error(`no application "${slug}" — see fund list`); return 2; }
      const p = await planFor(slug, { core, tracks, runAI, invoke, flags });
      p.file = writePlanFile(p.ctx.dir, planMarkdown(core, p));
      plans.push(p);
    }
    if (flags.json) { console.log(JSON.stringify(flags.all ? plans.map(planJson) : planJson(plans[0]), null, 2)); return 0; }
    if (!flags.all) {
      printPlan(core, plans[0]);
      console.log(`  (written to ${plans[0].file.slice(core.PATHS.apps.length + 1)})`);
      return 0;
    }
    // --all: one line per app, soonest deadline first.
    const order = (p) => { const d = daysLeft(core, p.fm.deadline); return p.closed ? 1e9 : d == null ? 1e6 : d; };
    plans.sort((a, b) => order(a) - order(b));
    console.log(`\n${'application'.padEnd(28)} ${'status'.padEnd(11)} ${'due'.padEnd(18)} ${'done'.padStart(5)}  next`);
    for (const p of plans) {
      const n = p.rows.filter((r) => r.done).length;
      const nx = p.closed ? `(${p.fm.status})` : p.next ? `${p.next.step.wait ? '⧗' : p.next.step.kind === 'human' ? '☐' : '→'} ${p.next.step.id}${p.lastFail ? ' (failed last run)' : ''}` : '✓ complete';
      console.log(`${p.slug.padEnd(28)} ${String(p.fm.status || '').padEnd(11)} ${dueLabel(core, p.fm.deadline).padEnd(18)} ${`${n}/${p.rows.length}`.padStart(5)}  ${nx}`);
    }
    // A step that failed its last run is stuck until a person fixes the cause; re-running it is not
    // "automatable" work, so it counts with the human queue.
    const auto = plans.filter((p) => !p.closed && p.next && p.next.step.kind !== 'human' && !p.lastFail);
    const waiting = plans.filter((p) => !p.closed && p.next && !p.next.step.wait && (p.next.step.kind === 'human' || p.lastFail));
    const watching = plans.filter((p) => !p.closed && p.next?.step.wait);
    console.log(`\n${auto.length} app(s) have automatable steps; ${waiting.length} wait for a person${watching.length ? `; ${watching.length} monitor(s) waiting on a date or a source change` : ''}.`);
    console.log(`next: ${auto.length ? `fund run ${auto[0].slug}` : 'fund queue'}`);
    return 0;
  },
};

const next = {
  name: 'next',
  help: '<slug>                     the single next step and the exact command',
  booleanFlags: ['json'],
  async run({ args, flags, core, runAI, tracks, invoke }) {
    const slug = args[0];
    if (!slug) { console.error('usage: next <slug>'); return 2; }
    if (!existsSync(join(core.appDir(slug), 'call.md'))) { console.error(`no application "${slug}" — see fund list`); return 2; }
    const p = await planFor(slug, { core, tracks, runAI, invoke, flags });
    if (flags.json) { console.log(JSON.stringify(planJson(p).next ? { ...planJson(p).next, command: command(p) } : { next: null, command: command(p) }, null, 2)); return 0; }
    if (p.closed) { console.log(`${slug}: status ${p.fm.status} — nothing to do.`); console.log(`next: ${command(p)}`); return 0; }
    if (!p.next) { console.log(`${slug}: every step is done.`); console.log('next: fund queue'); return 0; }
    const r = p.next;
    console.log(`${slug} → ${r.step.id} (${r.step.kind}, ~${r.step.estimate_h ?? 0}h): ${r.step.title}`);
    console.log(`  why: ${r.reason}`);
    if (p.lastFail) console.log(`  last run failed: ${p.lastFail}`);
    if (r.step.kind === 'human' && r.step.instructions) console.log(`  do: ${instructionsOf(r.step, p.ctx, slug)}`);
    if (r.step.kind === 'human' && p.fm.url && r.step.id === 'submit') console.log(`  form: ${p.fm.url}`);
    console.log(`next: ${command(p)}`);
    return 0;
  },
};

export default [plan, next];
