/**
 * GENERATED by client/scripts/sync-fonts.mjs from the pinned Fontsource packages. Do not edit.
 * Run `npm run fonts:sync` in client/ after changing the font packages or the script.
 *
 * Pure data (no imports) so design/tokens.ts, _document and the loader can all read it.
 */

export interface FontFileEntry {
  family: string;
  /** A number for static faces, a `min max` range for variable ones. */
  weight: number | string;
  style: "normal" | "italic";
  subset: "latin" | "latin-ext";
  /** Absolute URL, served from client/public/fonts, with a `?v=` content hash. */
  file: string;
}

/** Every self-hosted face declared in styles/fonts.generated.scss. */
export const FONT_FILES: ReadonlyArray<FontFileEntry> = [
  { family: "Passion One", weight: 400, style: "normal", subset: "latin", file: "/fonts/passion-one-latin-400-normal.woff2?v=eb49ce211d" },
  { family: "Passion One", weight: 400, style: "normal", subset: "latin-ext", file: "/fonts/passion-one-latin-ext-400-normal.woff2?v=6461918ac8" },
  { family: "Passion One", weight: 700, style: "normal", subset: "latin", file: "/fonts/passion-one-latin-700-normal.woff2?v=8cdeeec804" },
  { family: "Passion One", weight: 700, style: "normal", subset: "latin-ext", file: "/fonts/passion-one-latin-ext-700-normal.woff2?v=3e948dffc0" },
  { family: "Passion One", weight: 900, style: "normal", subset: "latin", file: "/fonts/passion-one-latin-900-normal.woff2?v=952f87c0d5" },
  { family: "Passion One", weight: 900, style: "normal", subset: "latin-ext", file: "/fonts/passion-one-latin-ext-900-normal.woff2?v=db5c14d258" },
  { family: "Bebas Neue", weight: 400, style: "normal", subset: "latin", file: "/fonts/bebas-neue-latin-400-normal.woff2?v=a7c90c8924" },
  { family: "Bebas Neue", weight: 400, style: "normal", subset: "latin-ext", file: "/fonts/bebas-neue-latin-ext-400-normal.woff2?v=16c95ce45a" },
  { family: "Nunito", weight: "200 1000", style: "normal", subset: "latin", file: "/fonts/nunito-latin-wght-normal.woff2?v=ba344451ea" },
  { family: "Nunito", weight: "200 1000", style: "normal", subset: "latin-ext", file: "/fonts/nunito-latin-ext-wght-normal.woff2?v=2c8d792869" },
  { family: "Nunito", weight: "200 1000", style: "italic", subset: "latin", file: "/fonts/nunito-latin-wght-italic.woff2?v=6cfcc3786d" },
  { family: "Nunito", weight: "200 1000", style: "italic", subset: "latin-ext", file: "/fonts/nunito-latin-ext-wght-italic.woff2?v=1bb48a49c8" },
  { family: "Roboto", weight: 500, style: "normal", subset: "latin", file: "/fonts/roboto-latin-500-normal.woff2?v=5bcc3aa180" },
];

/**
 * Brand family -> its metric-matched fallback families, in stack order (declared in the same
 * SCSS). The first is Arial-based; a second, "<Family> Fallback Android", carries Roboto where
 * Roboto's width differs from Arial's (the bold faces).
 */
export const FALLBACK_FAMILIES: Readonly<Record<string, ReadonlyArray<string>>> = {"Passion One":["Passion One Fallback","Passion One Fallback Android"],"Bebas Neue":["Bebas Neue Fallback"],"Nunito":["Nunito Fallback","Nunito Fallback Android"]};

/** The three brand faces `_document` preloads (latin subset). */
export const PRELOAD_FONT_FILES: ReadonlyArray<string> = ["/fonts/passion-one-latin-900-normal.woff2?v=952f87c0d5","/fonts/bebas-neue-latin-400-normal.woff2?v=a7c90c8924","/fonts/nunito-latin-wght-normal.woff2?v=ba344451ea"];

/** Package versions the files were copied from. */
export const FONT_SOURCE_VERSIONS: Readonly<Record<string, string>> = {"@fontsource/passion-one":"5.3.0","@fontsource/bebas-neue":"5.3.0","@fontsource-variable/nunito":"5.3.0","@fontsource/roboto":"5.3.0","@capsizecss/metrics":"4.3.0"};
