// GENERATED by scripts/sync-contracts.mjs from shared/analytics-core.ts. Do not edit this copy:
// edit shared/analytics-core.ts, then run `node scripts/sync-contracts.mjs`.
/**
 * The pure part of product analytics (plan F9), shared by the core app (`client/analytics`) and
 * Catnip Heist (`catnip-heist/src/analytics`, `catnip-heist/src/app/crash.ts`):
 *
 * - the event names and their F9 areas (one catalog; the property shapes stay in
 *   `client/analytics/events.ts`, which re-exports everything here);
 * - the consent key both apps read (`tt-analytics-consent`, same origin);
 * - the scrubber that strips personal data and secrets from error text;
 * - the per-session budget that caps and dedupes reports (at most N per session, one per code).
 *
 * No DOM, no imports, no framework. Framework-free and TypeScript 4.8 compatible. Edit here, then
 * run `node scripts/sync-contracts.mjs`.
 */

// ---------------------------------------------------------------------------------------------
// Consent and endpoint
// ---------------------------------------------------------------------------------------------

/** localStorage key of the player's analytics choice. `granted` is the only value that sends. */
export const CONSENT_STORAGE_KEY = 'tt-analytics-consent';

/** PostHog EU ingestion host (the only analytics host either app talks to). */
export const POSTHOG_EU_HOST = 'https://eu.i.posthog.com';

/** True only when the stored choice is `granted`. Never throws (blocked storage reads as denied). */
export function consentGrantedIn(storage: { getItem(key: string): string | null } | null | undefined): boolean {
    try {
        return !!storage && storage.getItem(CONSENT_STORAGE_KEY) === 'granted';
    } catch {
        return false;
    }
}

// ---------------------------------------------------------------------------------------------
// Event catalog
// ---------------------------------------------------------------------------------------------

export const ANALYTICS_EVENTS = {
    // Entry
    /** A landing call to action was pressed. */
    LANDING_CTA: 'landing_cta',
    /** The scene finished loading after the player picked a mode. */
    GAME_LOADED: 'game_loaded',
    /** The intro curtain lifted. */
    INTRO_LIFTED: 'intro_lifted',

    // Identity (G1, G9)
    GUEST_SESSION_CREATED: 'guest_session_created',
    AUTH_SHEET_SHOWN: 'auth_sheet_shown',
    AUTH_LINKED: 'auth_linked',
    AUTH_MERGED: 'auth_merged',
    AUTH_ERROR: 'auth_error',
    SAVE_NUDGE_SHOWN: 'save_nudge_shown',

    // Onboarding (G3)
    ONBOARDING_SHOWN: 'onboarding_shown',
    ONBOARDING_STEP_VIEWED: 'onboarding_step_viewed',
    STARTER_SELECTED: 'starter_selected',
    STARTER_NAMED: 'starter_named',
    STARTER_COMMITTED: 'starter_committed',
    ONBOARDING_SKIPPED: 'onboarding_skipped',
    FEATURED_CAT_FOLLOWED: 'featured_cat_followed',
    CAT_NAME_REJECTED: 'cat_name_rejected',
    CAT_NAME_REPORTED: 'cat_name_reported',

    // Runs (G10)
    FTUE_GATE_SHOWN: 'ftue_gate_shown',
    /** A run of a mode (or level) begins (RUN_BEGIN). */
    GAME_START: 'game_start',
    FTUE_HINT_SHOWN: 'ftue_hint_shown',
    FTUE_HINT_DONE: 'ftue_hint_done',
    LIFE_LOST: 'life_lost',
    /** The run ended without completing the level. */
    GAME_FAIL: 'game_fail',
    /** The run ended normally: level completed, or an endless run finished. */
    GAME_FINISH: 'game_finish',
    /** The player left the mode while a run was in progress. */
    GAME_QUIT: 'game_quit',
    FTUE_FIRST_CLEAR: 'ftue_first_clear',
    FTUE_ABANDON: 'ftue_abandon',

    // Heist (G2)
    HEIST_OPEN: 'heist_open',
    HEIST_RUN_COMPLETE: 'heist_run_complete',
    HEIST_SAVE: 'heist_save',
    HEIST_SIGNIN_PROMPT: 'heist_signin_prompt',
    HEIST_GUEST_CLAIM: 'heist_guest_claim',

    // Impact (G4, G5)
    IMPACT_TAB_VIEWED: 'impact_tab_viewed',
    PAW_EARNED: 'paw_earned',
    TREAT_SENT: 'treat_sent',
    PLEDGE_MADE: 'pledge_made',
    CLAIM_OPENED: 'claim_opened',
    IMPACT_PAGE_VIEWED: 'impact_page_viewed',

    // Health (G12, G13)
    APP_ERROR: 'app_error',
    GAME_FONT_FALLBACK: 'game_font_fallback',
    STOREFRONT_DEGRADED: 'storefront_degraded',
} as const;

export type AnalyticsEventKey = keyof typeof ANALYTICS_EVENTS;
export type AnalyticsEventName = typeof ANALYTICS_EVENTS[AnalyticsEventKey];

/** The F9 table areas, for dashboards and the catalog test. */
export type AnalyticsArea = 'entry' | 'identity' | 'onboarding' | 'runs' | 'heist' | 'impact' | 'health';

export const ANALYTICS_EVENT_AREAS: Record<AnalyticsEventName, AnalyticsArea> = {
    landing_cta: 'entry',
    game_loaded: 'entry',
    intro_lifted: 'entry',
    guest_session_created: 'identity',
    auth_sheet_shown: 'identity',
    auth_linked: 'identity',
    auth_merged: 'identity',
    auth_error: 'identity',
    save_nudge_shown: 'identity',
    onboarding_shown: 'onboarding',
    onboarding_step_viewed: 'onboarding',
    starter_selected: 'onboarding',
    starter_named: 'onboarding',
    starter_committed: 'onboarding',
    onboarding_skipped: 'onboarding',
    featured_cat_followed: 'onboarding',
    cat_name_rejected: 'onboarding',
    cat_name_reported: 'onboarding',
    ftue_gate_shown: 'runs',
    game_start: 'runs',
    ftue_hint_shown: 'runs',
    ftue_hint_done: 'runs',
    life_lost: 'runs',
    game_fail: 'runs',
    game_finish: 'runs',
    game_quit: 'runs',
    ftue_first_clear: 'runs',
    ftue_abandon: 'runs',
    heist_open: 'heist',
    heist_run_complete: 'heist',
    heist_save: 'heist',
    heist_signin_prompt: 'heist',
    heist_guest_claim: 'heist',
    impact_tab_viewed: 'impact',
    paw_earned: 'impact',
    treat_sent: 'impact',
    pledge_made: 'impact',
    claim_opened: 'impact',
    impact_page_viewed: 'impact',
    app_error: 'health',
    game_font_fallback: 'health',
    storefront_degraded: 'health',
};

/** Events the Heist build itself may send (the host page sends the rest of the heist area). */
export const HEIST_APP_EVENTS: AnalyticsEventName[] = ['heist_open', 'heist_run_complete', 'app_error'];

/** True when `name` is in the catalog. */
export function isAnalyticsEventName(name: unknown): name is AnalyticsEventName {
    return typeof name === 'string' && Object.prototype.hasOwnProperty.call(ANALYTICS_EVENT_AREAS, name);
}

// ---------------------------------------------------------------------------------------------
// Scrubbing
// ---------------------------------------------------------------------------------------------

/*
 * Removed: email addresses, JWTs (including `fb`-prefixed Firebase tokens), Stellar secret seeds and
 * account, muxed and contract addresses, 0x hex addresses and hashes, Mongo ObjectIds, IBANs, `did:`
 * ids, long digit runs (phone and national id numbers), hyphenated personal codes (`3800108-5718`),
 * space-grouped phone numbers (`5512 3456`), URL query strings and fragments, opaque tokens and ids
 * (Firebase UIDs, bearer and refresh tokens), and quoted names, including lowercase ones such as
 * "fluffy".
 *
 * Kept: a quoted identifier right after a browser TypeError word such as `reading`, `property` or
 * `execute`, so "Cannot read properties of undefined (reading 'sort')" stays useful. After our own
 * words (`key`, `event`, `scene`, `texture`, `animation`, `atlas`) the identifier must also look like
 * code (`cat_idle`, `ui.close`, `heist-01`, `catIdle`), so "texture 'fluffy'" loses the name. Stack
 * line and column numbers and bundle file names with their content hash (`app-3f2a…9c.js`) are kept.
 *
 * Known gap: a bare lowercase word after a TypeError word (`reading 'fluffy'`) is kept, since
 * property names look exactly like that.
 */

export const SCRUB_LIMITS = {
    message: 300,
    stack: 1200,
    stackFrames: 8,
    contextString: 120,
    contextKeys: 12,
} as const;

type ScrubRule = [RegExp, string];

// Order matters: the most specific shapes run first so a JWT is not first half-eaten by the hex
// rule, and a URL loses its query before names are looked for.
const SCRUB_RULES: ScrubRule[] = [
    // JWTs: three base64url segments, the first always starts with "eyJ".
    [/eyJ[A-Za-z0-9_-]{4,}\.[A-Za-z0-9_-]{4,}\.[A-Za-z0-9_-]*/g, '[jwt]'],
    // Emails.
    [/[A-Z0-9._%+-]+@[A-Z0-9-]+(?:\.[A-Z0-9-]+)*\.[A-Z]{2,}/gi, '[email]'],
    // Decentralised ids such as Privy's `did:privy:…`.
    [/\bdid:[a-z0-9]+:[A-Za-z0-9._:%-]+/g, '[did]'],
    // URL query strings and fragments (tokens, emails, ids ride in them). A trailing `:line:col` of
    // a stack frame stays outside the replaced part.
    [/([^\s?#"'`<>()]+)\?[^\s#"'`<>()]+?(?:#[^\s"'`<>()]*?)?((?::\d+){1,2})?(?=[\s"'`<>()]|$)/g, '$1?[query]$2'],
    [/((?:https?:)?\/\/[^\s#"'`<>()]+)#[^\s"'`<>()]+/g, '$1#[fragment]'],
    // Stellar strkeys: S secret seed, G account, M muxed, C contract.
    [/\bS[A-Z2-7]{55}\b/g, '[stellar-secret]'],
    [/\bM[A-Z2-7]{68}\b/g, '[stellar-address]'],
    [/\b[GC][A-Z2-7]{55}\b/g, '[stellar-address]'],
    // 0x addresses, tx hashes and other long hex.
    [/\b0x[0-9a-fA-F]{8,}\b/g, '[hex]'],
    // Mongo ObjectIds (24 hex) and longer bare hex digests.
    [/\b[0-9a-fA-F]{24,}\b/g, '[id]'],
    // IBANs, with or without the groups of four.
    [/\b[A-Z]{2}\d{2}(?: ?[A-Z0-9]{4}){2,7}(?: ?[A-Z0-9]{1,4})?\b/g, '[iban]'],
    // Phone numbers with a country code, and long digit runs such as the 11-digit Estonian
    // isikukood. Line:column pairs in stacks are shorter.
    [/\+\d[\d ()-]{7,}\d/g, '[number]'],
    [/\b\d{9,}\b/g, '[number]'],
    // Personal codes written with a hyphen (Finnish, Latvian, some Estonian forms), and phone
    // numbers grouped with spaces (`5512 3456`, `612 34567`).
    [/\b\d{6,7}-\d{4}\b/g, '[number]'],
    [/\b\d{3,4} \d{3,5}(?: \d{2,4})?\b/g, '[number]'],
];

// Opaque tokens and ids: 20+ base64url characters mixing letters and digits (Firebase UIDs, bearer
// and refresh tokens). Runs last, after the shapes above, and spares bundle file names such as
// `app-3f2a9c1b4e5d6f7a.js`.
const OPAQUE = /(?<![A-Za-z0-9_-])[A-Za-z0-9_-]{20,}(?![A-Za-z0-9_-])/g;
const FILE_EXTENSION = /^\.(?:m?js|cjs|jsx|tsx?|css|map|wasm|json|html?)\b/;

function scrubOpaque(text: string): string {
    return text.replace(OPAQUE, (match: string, offset: number) => {
        if (!/\d/.test(match) || !/[A-Za-z]/.test(match)) {
            return match;
        }
        if (FILE_EXTENSION.test(text.slice(offset + match.length))) {
            return match;
        }
        return '[token]';
    });
}

const QUOTED = /(['"`‘“])([^'"`‘’“”\n]{1,80})(['"`’”])/g;
/** The words after which a quoted string is code, not a person (`reading 'x'`, `execute 'x'`). */
const CODE_CONTEXT =
    /(?:reading|setting|property|properties|evaluating|execute|method|function|module|parameter|argument|field)\s*$/i;
/** Our own and Phaser's words (`key 'cat_idle'`); the quoted body must also look like code. */
const APP_CONTEXT = /(?:key|event|scene|texture|animation|atlas)\s*$/i;
/** What such a code string looks like: no spaces, identifier characters. */
const CODE_BODY = /^[\w$@./-]{1,60}$/;
/** Code, not a bare word: a `_ - . : /`, a digit, or an inner capital. */
const CODE_SHAPE = /[_.:/\d-]|[a-z][A-Z]/;
/** Our own placeholders, e.g. a `[query]` that ended up quoted. */
const PLACEHOLDER = /^\[[a-z-]+\]$/;

function scrubQuoted(text: string): string {
    return text.replace(QUOTED, (match: string, open: string, body: string, close: string, offset: number) => {
        if (PLACEHOLDER.test(body)) {
            return match;
        }
        const before = text.slice(Math.max(0, offset - 24), offset);
        if (CODE_BODY.test(body)) {
            if (CODE_CONTEXT.test(before)) {
                return match;
            }
            if (APP_CONTEXT.test(before) && CODE_SHAPE.test(body)) {
                return match;
            }
        }
        return `${open}[name]${close}`;
    });
}

function truncate(text: string, max: number): string {
    return text.length > max ? `${text.slice(0, max - 1)}…` : text;
}

/** Scrubs one string. Non-strings become an empty string. */
export function scrubText(value: unknown, max: number = SCRUB_LIMITS.message): string {
    if (typeof value !== 'string' || value.length === 0) {
        return '';
    }
    // Cap the work on pathological input before running the rules.
    let text = value.length > max * 8 ? value.slice(0, max * 8) : value;
    for (const [pattern, replacement] of SCRUB_RULES) {
        text = text.replace(pattern, replacement);
    }
    return truncate(scrubQuoted(scrubOpaque(text)), max);
}

/**
 * Scrubs a stack trace: keeps the first frames, drops the page origin so only the bundle path
 * remains, and applies the text rules.
 */
export function scrubStack(stack: unknown, origin?: string): string | null {
    if (typeof stack !== 'string' || stack.length === 0) {
        return null;
    }
    let lines = stack.split('\n').slice(0, SCRUB_LIMITS.stackFrames + 1);
    if (origin) {
        lines = lines.map(line => line.split(origin).join(''));
    }
    const text = scrubText(lines.map(line => line.trim()).join('\n'), SCRUB_LIMITS.stack);
    return text || null;
}

export type ScrubbedValue = string | number | boolean | null;

/**
 * Scrubs a flat context object: primitive values only, at most `SCRUB_LIMITS.contextKeys` keys, keys
 * limited to safe characters, strings scrubbed and shortened. Objects, arrays and functions are
 * dropped.
 */
export function scrubContext(context: unknown): Record<string, ScrubbedValue> {
    const out: Record<string, ScrubbedValue> = {};
    if (!context || typeof context !== 'object') {
        return out;
    }
    let kept = 0;
    const record = context as Record<string, unknown>;
    for (const key of Object.keys(record)) {
        if (kept >= SCRUB_LIMITS.contextKeys) {
            break;
        }
        if (!/^[a-z][a-z0-9_]{0,39}$/.test(key)) {
            continue;
        }
        const value = record[key];
        if (typeof value === 'string') {
            out[key] = scrubText(value, SCRUB_LIMITS.contextString);
        } else if (typeof value === 'number') {
            out[key] = Number.isFinite(value) ? value : null;
        } else if (typeof value === 'boolean' || value === null) {
            out[key] = value;
        } else {
            continue;
        }
        kept += 1;
    }
    return out;
}

/** A route without its query, fragment or ids: `/cats/[id]` style. */
export function scrubRoute(path: unknown): string {
    if (typeof path !== 'string') {
        return '';
    }
    const bare = path.split(/[?#]/)[0] || '/';
    return scrubText(bare, SCRUB_LIMITS.contextString);
}

// ---------------------------------------------------------------------------------------------
// Session budget (cap and dedupe)
// ---------------------------------------------------------------------------------------------

/** What a budget remembers: how many reports were sent this session, and for which codes. */
export interface SessionBudgetState {
    count: number;
    codes: string[];
}

/** Where a budget keeps its state (sessionStorage in the apps, a plain object in tests). */
export interface SessionBudgetStore {
    read(): SessionBudgetState;
    write(state: SessionBudgetState): void;
}

const REPORT_CODE = /^[a-z0-9][a-z0-9_.:-]{0,63}$/;

/** A lowercase machine code, or `unknown` for anything else (so a code can never carry data). */
export function normaliseCode(code: unknown): string {
    if (typeof code !== 'string') {
        return 'unknown';
    }
    const lower = code.trim().toLowerCase();
    return REPORT_CODE.test(lower) ? lower : 'unknown';
}

/** Parses a stored budget; anything malformed is an empty budget. */
export function parseBudgetState(raw: string | null | undefined): SessionBudgetState | null {
    if (!raw) {
        return null;
    }
    try {
        const parsed = JSON.parse(raw) as { count?: unknown; codes?: unknown };
        const count = Number(parsed && parsed.count);
        const codes = parsed && Array.isArray(parsed.codes)
            ? (parsed.codes as unknown[]).filter((code): code is string => typeof code === 'string')
            : [];
        return { count: Number.isFinite(count) ? count : 0, codes };
    } catch {
        return null;
    }
}

/**
 * A budget kept under `key` in a Storage-like object, with an in-memory copy for when the storage
 * is missing or blocked (the budget then holds for this page view).
 */
export function storageBudgetStore(
    key: string,
    storage: () => { getItem(key: string): string | null; setItem(key: string, value: string): void } | null | undefined
): SessionBudgetStore {
    let memory: SessionBudgetState = { count: 0, codes: [] };
    return {
        read() {
            try {
                const target = storage();
                const parsed = parseBudgetState(target ? target.getItem(key) : null);
                if (parsed) {
                    memory = parsed;
                }
            } catch {
                // Unreadable: keep the in-memory state.
            }
            return memory;
        },
        write(state) {
            memory = state;
            try {
                const target = storage();
                if (target) {
                    target.setItem(key, JSON.stringify(state));
                }
            } catch {
                // Storage blocked.
            }
        },
    };
}

export interface SessionBudget {
    /**
     * Takes one slot for `code`. Returns the 1-based report index, or 0 when the session is out of
     * budget or the code was already reported (nothing is counted then).
     */
    take(code: string): number;
}

/** At most `max` reports per session and one per (normalised) code. */
export function createSessionBudget(max: number, store: SessionBudgetStore): SessionBudget {
    return {
        take(code) {
            const key = normaliseCode(code);
            const state = store.read();
            if (state.count >= max || state.codes.indexOf(key) !== -1) {
                return 0;
            }
            const next = { count: state.count + 1, codes: state.codes.concat([key]) };
            store.write(next);
            return next.count;
        },
    };
}
