// GENERATED by scripts/sync-contracts.mjs from shared/heist-bridge.ts. Do not edit this copy:
// edit shared/heist-bridge.ts, then run `node scripts/sync-contracts.mjs`.
/**
 * Messages between the `/heist` host page and the embedded Catnip Heist iframe (plan G2 layer 1).
 *
 * Every message is `{ channel: HEIST_BRIDGE_CHANNEL, v: HEIST_BRIDGE_VERSION, type, ... }` sent with
 * `postMessage`. Origin and source checks on both sides are hygiene only: the iframe is same-origin,
 * so it is not a security boundary, and the backend re-verifies every run by replay.
 *
 * Framework-free and TypeScript 4.8 compatible. Edit here, then run `node scripts/sync-contracts.mjs`.
 */

import { HEIST_MAX_ID_LENGTH, HEIST_MAX_RUNS, HEIST_MAX_TICKS } from './caps';

export const HEIST_BRIDGE_CHANNEL = 'tt-heist-bridge';
export const HEIST_BRIDGE_VERSION = 1;

/** How often the host resends `hello` until the Heist answers `ready`, and for how long. */
export const HEIST_HELLO_RETRY_MS = 500;
export const HEIST_HELLO_TIMEOUT_MS = 10000;

// ---------------------------------------------------------------------------------------------
// Payloads
// ---------------------------------------------------------------------------------------------

/** Safe-area insets in CSS pixels. `env(safe-area-inset-*)` is 0 inside an iframe, so the host sends them. */
export interface HeistInsets {
    top: number;
    right: number;
    bottom: number;
    left: number;
}

/** Server-side best result for one level, merged into the Heist's local progress. */
export interface HeistLevelProgress {
    won: boolean;
    bestScore: number;
    /** Star bitmask: 1 heist complete, 2 all catnip, 4 clean and quick. */
    stars: number;
}

export interface HeistProgress {
    /** Keyed by level id (`heist-01` ...). */
    levels: Record<string, HeistLevelProgress>;
}

/** One run length of inputs: `[dx, dy, flags, count]`, flags 1 swap, 2 interact, 4 meow. */
export type HeistInputRun = [number, number, number, number];

/** The input log a run posts for replay verification. Mirrors `InputLog` in `catnip-heist/src/sim/replay.ts`. */
export interface HeistRunLog {
    levelId: string;
    simVersion: number;
    seed: number;
    catIds: [string, string];
    ticks: number;
    runs: HeistInputRun[];
    finalHash?: number;
    score?: number;
    spottedCount?: number;
    coins?: number;
}

/** Outcome of the host's save attempt for a run. */
export type HeistSaveStatus = 'saved' | 'queued' | 'signed-out' | 'rejected' | 'error';

// ---------------------------------------------------------------------------------------------
// Host to Heist
// ---------------------------------------------------------------------------------------------

interface BridgeEnvelope {
    channel: typeof HEIST_BRIDGE_CHANNEL;
    v: number;
}

export interface HeistHelloMessage extends BridgeEnvelope {
    type: 'hello';
}

export interface HeistSessionMessage extends BridgeEnvelope {
    type: 'session';
    signedIn: boolean;
    progress: HeistProgress | null;
    insets: HeistInsets;
}

export interface HeistSaveResultMessage extends BridgeEnvelope {
    type: 'save-result';
    runId: string;
    status: HeistSaveStatus;
    /** An `ErrorCode` from `errors.ts` when the backend rejected the run. */
    code?: string;
}

export interface HeistPauseMessage extends BridgeEnvelope {
    type: 'pause';
}

export interface HeistResumeMessage extends BridgeEnvelope {
    type: 'resume';
}

/**
 * The shell's sound settings (plan G14 "Audio": one switch for all sound). Volumes are 0..1 on the
 * shell's scale; the Heist maps them onto its own mix and applies them for this visit only, without
 * touching its standalone mute preference. Sent after `ready` and on every change.
 */
export interface HeistAudioMessage extends BridgeEnvelope {
    type: 'audio';
    muted: boolean;
    musicVolume: number;
    effectsVolume: number;
}

export type HostToHeistMessage =
    | HeistHelloMessage
    | HeistSessionMessage
    | HeistSaveResultMessage
    | HeistPauseMessage
    | HeistResumeMessage
    | HeistAudioMessage;

// ---------------------------------------------------------------------------------------------
// Heist to host
// ---------------------------------------------------------------------------------------------

export interface HeistReadyMessage extends BridgeEnvelope {
    type: 'ready';
}

export interface HeistRunCompleteMessage extends BridgeEnvelope {
    type: 'run-complete';
    /** Client-generated id; the backend dedupes on it (`HEIST_DUPLICATE`). */
    runId: string;
    won: boolean;
    levelId: string;
    log: HeistRunLog;
}

export interface HeistRequestSignInMessage extends BridgeEnvelope {
    type: 'request-sign-in';
}

export interface HeistExitMessage extends BridgeEnvelope {
    type: 'exit';
}

export type HeistToHostMessage =
    | HeistReadyMessage
    | HeistRunCompleteMessage
    | HeistRequestSignInMessage
    | HeistExitMessage;

export type HeistBridgeMessage = HostToHeistMessage | HeistToHostMessage;

// ---------------------------------------------------------------------------------------------
// Builders and guards
// ---------------------------------------------------------------------------------------------

/** A message without its envelope. Distributes over unions, so a body matches exactly one message type. */
export type HeistMessageBody<M> = M extends unknown ? Omit<M, 'channel' | 'v'> : never;

/** Adds the channel and version to a message body. */
export function heistMessage<M extends HeistBridgeMessage>(body: HeistMessageBody<M>): M {
    return { ...(body as object), channel: HEIST_BRIDGE_CHANNEL, v: HEIST_BRIDGE_VERSION } as M;
}

const HOST_TO_HEIST_TYPES = ['hello', 'session', 'save-result', 'pause', 'resume', 'audio'];
const HEIST_TO_HOST_TYPES = ['ready', 'run-complete', 'request-sign-in', 'exit'];
const SAVE_STATUSES = ['saved', 'queued', 'signed-out', 'rejected', 'error'];

const isRecord = (value: unknown): value is Record<string, unknown> =>
    !!value && typeof value === 'object' && !Array.isArray(value);

const isFiniteNumber = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value);

function isEnvelope(value: unknown): value is Record<string, unknown> & BridgeEnvelope & { type: string } {
    return (
        isRecord(value) &&
        value.channel === HEIST_BRIDGE_CHANNEL &&
        value.v === HEIST_BRIDGE_VERSION &&
        typeof value.type === 'string'
    );
}

const isUnitInterval = (value: unknown): value is number => isFiniteNumber(value) && value >= 0 && value <= 1;

function isInsets(value: unknown): value is HeistInsets {
    return (
        isRecord(value) &&
        isFiniteNumber(value.top) &&
        isFiniteNumber(value.right) &&
        isFiniteNumber(value.bottom) &&
        isFiniteNumber(value.left)
    );
}

function isProgress(value: unknown): value is HeistProgress {
    if (!isRecord(value) || !isRecord(value.levels)) {
        return false;
    }
    const levels = value.levels;
    return Object.keys(levels).every(key => {
        const level = levels[key];
        return (
            isRecord(level) &&
            typeof level.won === 'boolean' &&
            isFiniteNumber(level.bestScore) &&
            isFiniteNumber(level.stars)
        );
    });
}

const isNonNegativeInteger = (value: unknown): value is number =>
    typeof value === 'number' && Number.isInteger(value) && value >= 0;

/** A non-empty string no longer than `HEIST_MAX_ID_LENGTH`. */
const isBoundedId = (value: unknown): value is string =>
    typeof value === 'string' && value.length > 0 && value.length <= HEIST_MAX_ID_LENGTH;

const AXIS_VALUES = [-1, 0, 1];
/** Seeds are unsigned 32-bit (`catnip-heist/src/main.ts`). */
const MAX_UINT32 = 0xffffffff;
/** Highest valid flags value: swap (1) | interact (2) | meow (4). */
const MAX_INPUT_FLAGS = 7;

/**
 * Structural check of a run log, bounded so a hostile log cannot make the backend replay expensive:
 * integer fields, at most `HEIST_MAX_TICKS` ticks and `HEIST_MAX_RUNS` runs, every run `count >= 1`,
 * the run counts summing to `ticks`, and ids capped at `HEIST_MAX_ID_LENGTH`. The backend replay is
 * still the real verification.
 */
export function isHeistRunLog(value: unknown): value is HeistRunLog {
    if (!isRecord(value)) {
        return false;
    }
    const { levelId, simVersion, seed, catIds, ticks, runs } = value;
    if (
        !isBoundedId(levelId) ||
        !isNonNegativeInteger(simVersion) ||
        !isNonNegativeInteger(seed) ||
        seed > MAX_UINT32 ||
        !isNonNegativeInteger(ticks) ||
        ticks > HEIST_MAX_TICKS ||
        !Array.isArray(catIds) ||
        catIds.length !== 2 ||
        !catIds.every(isBoundedId) ||
        !Array.isArray(runs) ||
        runs.length > HEIST_MAX_RUNS
    ) {
        return false;
    }
    let total = 0;
    for (let index = 0; index < runs.length; index += 1) {
        const run: unknown = runs[index];
        if (!Array.isArray(run) || run.length !== 4) {
            return false;
        }
        const [dx, dy, flags, count] = run as unknown[];
        if (
            AXIS_VALUES.indexOf(dx as number) === -1 ||
            AXIS_VALUES.indexOf(dy as number) === -1 ||
            !isNonNegativeInteger(flags) ||
            flags > MAX_INPUT_FLAGS ||
            !isNonNegativeInteger(count) ||
            count < 1
        ) {
            return false;
        }
        total += count;
        if (total > ticks) {
            return false;
        }
    }
    return total === ticks;
}

/** True for a well-formed message the host may send to the Heist. */
export function isHostToHeistMessage(value: unknown): value is HostToHeistMessage {
    if (!isEnvelope(value) || HOST_TO_HEIST_TYPES.indexOf(value.type) === -1) {
        return false;
    }
    switch (value.type) {
        case 'session':
            return (
                typeof value.signedIn === 'boolean' &&
                (value.progress === null || isProgress(value.progress)) &&
                isInsets(value.insets)
            );
        case 'save-result':
            return (
                isBoundedId(value.runId) &&
                SAVE_STATUSES.indexOf(value.status as string) !== -1 &&
                (value.code === undefined || typeof value.code === 'string')
            );
        case 'audio':
            return (
                typeof value.muted === 'boolean' &&
                isUnitInterval(value.musicVolume) &&
                isUnitInterval(value.effectsVolume)
            );
        default:
            return true;
    }
}

/** True for a well-formed message the Heist may send to the host. */
export function isHeistToHostMessage(value: unknown): value is HeistToHostMessage {
    if (!isEnvelope(value) || HEIST_TO_HOST_TYPES.indexOf(value.type) === -1) {
        return false;
    }
    if (value.type === 'run-complete') {
        return (
            isBoundedId(value.runId) &&
            typeof value.won === 'boolean' &&
            isBoundedId(value.levelId) &&
            isHeistRunLog(value.log) &&
            (value.log as HeistRunLog).levelId === value.levelId
        );
    }
    return true;
}
