#!/usr/bin/env node
/**
 * Generates `styles/tokens.css` from `design/tokens.ts` (plan F3.1).
 *
 *   node scripts/build-tokens.mjs          write styles/tokens.css
 *   node scripts/build-tokens.mjs --check  exit 1 if styles/tokens.css is stale (CI)
 *
 * Each colour becomes a space-separated RGB triplet (`--tt-night-900: 11 8 32;`) so Tailwind can
 * apply an alpha (`rgb(var(--tt-night-900) / <alpha-value>)`). Layers become `--tt-z-<name>`.
 *
 * `design/tokens.ts` is loaded with Node's built-in type stripping (Node 22.18+), falling back to
 * the jiti that Tailwind already depends on.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, relative } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokensPath = join(root, "design", "tokens.ts");
const outPath = join(root, "styles", "tokens.css");

async function loadTokens() {
  // Loading a .ts file natively warns about the typeless package.json and, on some 22.x
  // releases, about experimental type stripping. Neither matters for a pure data module.
  const emitWarning = process.emitWarning;
  process.emitWarning = (warning, ...rest) => {
    const text = String(warning?.message ?? warning);
    const code = typeof rest[0] === "object" ? rest[0]?.code : rest[1];
    if (code === "MODULE_TYPELESS_PACKAGE_JSON" || /type stripping|Reparsing as ES module/i.test(text)) return;
    return emitWarning.call(process, warning, ...rest);
  };
  try {
    return await import(pathToFileURL(tokensPath).href);
  } catch (error) {
    const require = createRequire(import.meta.url);
    let jiti;
    try {
      jiti = require("jiti");
    } catch {
      throw error;
    }
    return jiti(import.meta.url, { interopDefault: true })(tokensPath);
  } finally {
    process.emitWarning = emitWarning;
  }
}

/** `#rrggbb` or `#rgb` to `"r g b"`. Throws on anything else so a typo never ships. */
export function hexToTriplet(hex) {
  const match = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(hex);
  if (!match) throw new Error(`Not a hex colour: ${hex}`);
  let digits = match[1];
  if (digits.length === 3) digits = [...digits].map((d) => d + d).join("");
  const value = parseInt(digits, 16);
  return `${(value >> 16) & 255} ${(value >> 8) & 255} ${value & 255}`;
}

export function renderTokensCss({ TT_COLORS, LAYERS }) {
  const lines = [
    "/*",
    " * GENERATED by scripts/build-tokens.mjs from design/tokens.ts. Do not edit by hand.",
    " * Run `npm run tokens:build` after changing the tokens.",
    " */",
    ":root {",
  ];
  for (const [name, hex] of Object.entries(TT_COLORS)) {
    lines.push(`  --tt-${name}: ${hexToTriplet(hex)}; /* ${hex.toLowerCase()} */`);
  }
  for (const [name, z] of Object.entries(LAYERS)) {
    if (!Number.isInteger(z)) throw new Error(`Layer ${name} is not an integer: ${z}`);
    lines.push(`  --tt-z-${name}: ${z};`);
  }
  lines.push("}", "");
  return lines.join("\n");
}

async function main() {
  const check = process.argv.includes("--check");
  const css = renderTokensCss(await loadTokens());
  const rel = relative(process.cwd(), outPath) || outPath;
  if (check) {
    let current = "";
    try {
      current = readFileSync(outPath, "utf8");
    } catch {
      // Missing file counts as stale.
    }
    if (current !== css) {
      console.error(`${rel} is stale. Run: npm run tokens:build`);
      process.exit(1);
    }
    console.log(`${rel} is up to date.`);
    return;
  }
  writeFileSync(outPath, css);
  console.log(`Wrote ${rel}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
