// GENERATED by scripts/sync-contracts.mjs from shared/home-yard.ts. Do not edit this copy:
// edit shared/home-yard.ts, then run `node scripts/sync-contracts.mjs`.
/**
 * The Cat Yard as the client's HOME (`/game` -> MY HOME).
 *
 * catnip-heist builds `src/home/index.ts` into `client/public/heist-game/build/home-<hash>.js`
 * (`npm run build:client`). The client imports that module at runtime (browser only, same origin,
 * no remote code) and calls `createHomeYard` with the player's own cats. Nothing is posted across
 * documents: the yard renders into an element of the client's page.
 *
 * HOME writes no scores. Feeding still goes through the client's cat status save, never here.
 *
 * Framework-free and TypeScript 4.8 compatible. Edit here, then run `node scripts/sync-contracts.mjs`.
 */

/** Bumped on any breaking change to the API below; the client refuses a module with another one. */
export const HOME_YARD_API_VERSION = 1;

/** Most cats HOME shows at once (the active cat always among them). */
export const HOME_YARD_MAX_CATS = 24;

/** One of the player's cats, as the client hands it to the yard. */
export interface HomeYardCat {
  id: string;
  name: string;
  /** The cat's spritesheet (48 px frames, 15 columns, rows in the cat row order). */
  sheetUrl: string;
  /** The player's active cat (`profile.cat`). */
  active: boolean;
  /** EAT below the maximum: the feed button shows for the active cat. */
  hungry: boolean;
  tier?: string;
  type?: string;
  /** Blessed cats get a soft glow in their ability colour. */
  blessed?: boolean;
  /** Newest first is kept when there are more cats than the cap (ISO date). */
  createdAt?: string;
}

export interface HomeYardReady {
  /** Cats placed in the yard. */
  loaded: number;
  /** Ids whose sheets failed to load (left out, or the active one shown with a stand-in sheet). */
  failed: string[];
}

export interface HomeYardOptions {
  /** URL of the built Heist's assets folder, with a trailing slash (`/heist-game/assets/`). */
  assetBase: string;
  cats: HomeYardCat[];
  /** `auto` lets the yard probe the frame rate. */
  quality?: 'auto' | 'low' | 'high';
  reducedMotion?: boolean;
  /** Default HOME_YARD_MAX_CATS. */
  maxCats?: number;
  /** Lift the yard's name card this far above the bottom safe area (room for the client's HUD). */
  cardBottomPx?: number;
  /** A cat was tapped (its name card opened) or the card closed (null). */
  onSelect?(id: string | null): void;
  /** SELECT on the name card of a cat that is not the active one. */
  onChoose?(id: string): void;
  /** The cat sent by `feed` reached the bowls and started eating. */
  onEating?(id: string): void;
  /** The cat finished eating (after `feed`). */
  onFed?(id: string): void;
  /** A cat's sheet failed to load. */
  onSheetError?(id: string): void;
  /** The WebGL context was lost: the yard stopped drawing and will not recover this visit. */
  onContextLost?(): void;
}

export interface HomeYardAPI {
  readonly ready: Promise<HomeYardReady>;
  /** New cats or a new active cat. Same ids: updates in place; other ids: rebuilds the yard. */
  setCats(cats: HomeYardCat[]): void;
  /**
   * Feeding time for one cat; resolves when it has eaten (onFed fires first). A rebuild or dispose
   * during the meal resolves it without onFed.
   */
  feed(id: string): Promise<void>;
  select(id: string | null): void;
  focus(id: string): void;
  start(): void;
  stop(): void;
  dispose(): void;
  stats(): unknown;
  /** Where each cat is on screen, in CSS px (QA and end-to-end tests). */
  screenPositions(): { id: string; x: number; y: number; visible: boolean }[];
}

export interface HomeYardModule {
  HOME_YARD_API_VERSION: number;
  createHomeYard(el: HTMLElement, options: HomeYardOptions): HomeYardAPI;
}

/** A loaded module the client can use: the right shape and the same API version. */
export function isHomeYardModule(value: unknown): value is HomeYardModule {
  if (!value || typeof value !== 'object') return false;
  const m = value as Partial<HomeYardModule>;
  return m.HOME_YARD_API_VERSION === HOME_YARD_API_VERSION && typeof m.createHomeYard === 'function';
}

/**
 * The cats HOME shows: unique ids with a sheet, at most `max`, the active cat always first, then
 * the newest (by createdAt, else their order).
 */
export function pickHomeYardCats(cats: readonly HomeYardCat[], max: number = HOME_YARD_MAX_CATS): HomeYardCat[] {
  const seen = new Set<string>();
  const usable: { cat: HomeYardCat; order: number }[] = [];
  cats.forEach((cat, order) => {
    if (!cat || !cat.id || !cat.sheetUrl || seen.has(cat.id)) return;
    seen.add(cat.id);
    usable.push({ cat, order });
  });
  const time = (c: HomeYardCat) => {
    const t = c.createdAt ? Date.parse(c.createdAt) : NaN;
    return Number.isFinite(t) ? t : -Infinity;
  };
  usable.sort((a, b) => {
    if (a.cat.active !== b.cat.active) return a.cat.active ? -1 : 1;
    const ta = time(a.cat), tb = time(b.cat);
    if (ta !== tb) return tb > ta ? 1 : -1;
    return a.order - b.order;
  });
  const cap = Math.max(1, Math.floor(max));
  return usable.slice(0, cap).map((u) => u.cat);
}

/** Whether two cat lists hold the same ids (in any order): then the yard updates in place. */
export function sameHomeYardIds(a: readonly HomeYardCat[], b: readonly HomeYardCat[]): boolean {
  if (a.length !== b.length) return false;
  const ids = new Set(a.map((c) => c.id));
  return b.every((c) => ids.has(c.id));
}
