// GENERATED by `fund facts build` from funding/framework/facts/facts.json. Do not edit this file:
// edit facts.json, then run `node funding/framework/bin/fund.mjs facts build`.
// The Heist fetches PUBLIC_FACTS_PATH (HEIST_FACTS_URL) at runtime; this copy is the offline fallback.

/** Every fact id a Heist surface may cite (plan F7.1). */
// prettier-ignore
export type FactId = 'C-001' | 'C-004' | 'C-005' | 'F-001' | 'F-003' | 'F-004' | 'F-011' | 'F-013' | 'F-023' | 'F-025' | 'F-026' | 'L-countries' | 'L-disbursed' | 'L-heists' | 'L-match' | 'L-players' | 'L-rail' | 'L-treats';

// prettier-ignore
export type FactStatus = 'verified' | 'company-reported' | 'sei-era' | 'live';
// prettier-ignore
export type FactSurface = 'landing' | 'game' | 'heist' | 'impact' | 'shelter-payouts' | 'store';

// prettier-ignore
export interface PublicFact {
  id: FactId;
  /** Public wording. For live entries it is a template: "{n}" or "{amount}". */
  display: string;
  /** Wording for app builds (the Capacitor app, the Heist included) when display has money or chain words (R10). */
  appDisplay: string | null;
  /** Null for live metrics: read them from `live.endpoint`. */
  value: number | string | null;
  unit: string | null;
  status: FactStatus;
  tense: 'past' | 'present' | 'future';
  asOf: string | null;
  checkedAt: string;
  /** Null only for SEI-era history, which never goes stale. */
  maxAgeDays: number | null;
  surfaces: FactSurface[];
  sourceUrl: string | null;
  key?: string;
  /** A shorter wording for tight spaces (the lobby strip); the drawer still shows display. */
  short?: string;
  /** Token Tails holds records behind this entry and answers requests for them. */
  recordsOnRequest?: true;
  chain?: 'sei' | 'stellar' | 'arc' | 'skale';
  live?: { endpoint: string; path: string };
  goal?: { startDate: string; endDate: string };
  /**
   * A goal's meter: the USDC that came in to `wallets` (each inside its block range) on `chainId`,
   * summed from `inflowLog` Transfer logs by the backend (GET /shelter/goal/:id). `wallet` is where
   * money arrives today; `token` and `startBalance` serve the balance fallback (one wallet, nonce 0).
   */
  campaign?: { chainId: number; fromBlock: number | null; wallet: string | null; handover: 'held-by-token-tails' | 'handed-over'; wallets: { wallet: string; fromBlock: number; toBlock: number | null; holder: 'token-tails' | 'shelter' }[]; inflowLog: { address: string; decimals: number } | null; token: { address: string; decimals: number } | null; startBalance: string };
}

/** Where the web app and the Heist fetch the current public facts. */
// prettier-ignore
export const PUBLIC_FACTS_PATH = '/facts/facts.json';

// prettier-ignore
export const FACT_IDS: readonly FactId[] = ["C-001","C-004","C-005","F-001","F-003","F-004","F-011","F-013","F-023","F-025","F-026","L-countries","L-disbursed","L-heists","L-match","L-players","L-rail","L-treats"];

// prettier-ignore
export const FACTS: Record<FactId, PublicFact> = {
  "C-001": {
    "id": "C-001",
    "display": "Goal: 50,000 USDC for Pink Paw by 30 Sep 2027",
    "appDisplay": null,
    "value": "50000",
    "unit": "USDC",
    "status": "verified",
    "tense": "future",
    "asOf": "2026-10-04",
    "checkedAt": "2026-10-04",
    "maxAgeDays": 125,
    "surfaces": [
      "shelter-payouts"
    ],
    "sourceUrl": null,
    "key": "campaign",
    "chain": "arc",
    "goal": {
      "startDate": "2026-10-02",
      "endDate": "2027-09-30"
    },
    "campaign": {
      "chainId": 5042,
      "fromBlock": 23790973,
      "wallet": "0xE299299b846Ba629f5A591dBF4F562bcC07A0f37",
      "handover": "held-by-token-tails",
      "wallets": [
        {
          "wallet": "0xe299299b846ba629f5a591dbf4f562bcc07a0f37",
          "fromBlock": 23790973,
          "toBlock": null,
          "holder": "token-tails"
        }
      ],
      "inflowLog": {
        "address": "0xfffffffffffffffffffffffffffffffffffffffe",
        "decimals": 18
      },
      "token": {
        "address": "0x3600000000000000000000000000000000000000",
        "decimals": 6
      },
      "startBalance": "0"
    }
  },
  "C-004": {
    "id": "C-004",
    "display": "0.01 USDC treat",
    "appDisplay": "a $0.01 treat",
    "value": "0.01",
    "unit": "USDC",
    "status": "verified",
    "tense": "present",
    "asOf": "2026-09-30",
    "checkedAt": "2026-09-30",
    "maxAgeDays": 120,
    "surfaces": [
      "heist",
      "shelter-payouts"
    ],
    "sourceUrl": null,
    "key": "treat_amount",
    "chain": "arc"
  },
  "C-005": {
    "id": "C-005",
    "display": "1 USDC of treats a day",
    "appDisplay": "$1 of treats a day",
    "value": "1",
    "unit": "USDC",
    "status": "verified",
    "tense": "present",
    "asOf": "2026-09-30",
    "checkedAt": "2026-09-30",
    "maxAgeDays": 120,
    "surfaces": [
      "heist",
      "shelter-payouts"
    ],
    "sourceUrl": null,
    "key": "daily_budget",
    "chain": "arc"
  },
  "F-001": {
    "id": "F-001",
    "display": "540K+ registered players, all time (Apr 2026, company-reported)",
    "appDisplay": null,
    "value": 542000,
    "unit": "players",
    "status": "company-reported",
    "tense": "past",
    "asOf": "2026-04",
    "checkedAt": "2026-04",
    "maxAgeDays": 365,
    "surfaces": [
      "landing"
    ],
    "sourceUrl": null
  },
  "F-003": {
    "id": "F-003",
    "display": "324K+ active wallets in the peak week on SEI (Nov 2025)",
    "appDisplay": null,
    "value": 324422,
    "unit": "wallets",
    "status": "sei-era",
    "tense": "past",
    "asOf": "2025-11-17",
    "checkedAt": "2026-09-27",
    "maxAgeDays": null,
    "surfaces": [
      "landing"
    ],
    "sourceUrl": null,
    "chain": "sei"
  },
  "F-004": {
    "id": "F-004",
    "display": "875K+ transactions in the peak week on SEI (Nov 2025)",
    "appDisplay": null,
    "value": 875907,
    "unit": "transactions",
    "status": "sei-era",
    "tense": "past",
    "asOf": "2025-11-17",
    "checkedAt": "2026-09-27",
    "maxAgeDays": null,
    "surfaces": [
      "landing"
    ],
    "sourceUrl": null,
    "chain": "sei"
  },
  "F-011": {
    "id": "F-011",
    "display": "180K+ on X (Sep 2026)",
    "appDisplay": null,
    "value": 181010,
    "unit": "followers",
    "status": "verified",
    "tense": "present",
    "asOf": "2026-09-27",
    "checkedAt": "2026-09-27",
    "maxAgeDays": 90,
    "surfaces": [
      "landing"
    ],
    "sourceUrl": "https://api.fxtwitter.com/tokentails"
  },
  "F-013": {
    "id": "F-013",
    "display": "40 influencer cats onboarded (Apr 2026, company-reported)",
    "appDisplay": null,
    "value": "40 cats across 23 IG/TikTok profiles",
    "unit": "cats",
    "status": "company-reported",
    "tense": "past",
    "asOf": "2026-04",
    "checkedAt": "2026-04",
    "maxAgeDays": 365,
    "surfaces": [
      "landing"
    ],
    "sourceUrl": null
  },
  "F-023": {
    "id": "F-023",
    "display": "Shelter-cat event at Le Chat-Rivari café, Paris (Apr 2026, company-reported)",
    "appDisplay": null,
    "value": "Shelter-cat event at Le Chat-Rivari café, Paris, 2026-04-17",
    "unit": null,
    "status": "company-reported",
    "tense": "past",
    "asOf": "2026-04-17",
    "checkedAt": "2026-10-04",
    "maxAgeDays": 365,
    "surfaces": [
      "landing"
    ],
    "sourceUrl": "https://x.com/tokentails/status/2046611480263467341"
  },
  "F-025": {
    "id": "F-025",
    "display": "Now: Stellar NFTs",
    "appDisplay": null,
    "value": "Stellar (Soroban NFTs, custodial Stellar wallet per user)",
    "unit": null,
    "status": "verified",
    "tense": "present",
    "asOf": "2026-09",
    "checkedAt": "2026-09",
    "maxAgeDays": 180,
    "surfaces": [
      "landing"
    ],
    "sourceUrl": null,
    "chain": "stellar"
  },
  "F-026": {
    "id": "F-026",
    "display": "$40K+ donated directly in crypto and goods (Oct 2026, company-reported)",
    "appDisplay": "$40K+ donated directly in money and goods (Oct 2026, company-reported)",
    "value": 40000,
    "unit": "USD",
    "status": "company-reported",
    "tense": "past",
    "asOf": "2026-10-03",
    "checkedAt": "2026-10-03",
    "maxAgeDays": 365,
    "surfaces": [
      "landing",
      "game",
      "impact"
    ],
    "sourceUrl": null,
    "key": "donated_direct_total",
    "short": "$40K+ donated in crypto and goods"
  },
  "L-countries": {
    "id": "L-countries",
    "display": "{n} partner countries",
    "appDisplay": null,
    "value": null,
    "unit": "countries",
    "status": "live",
    "tense": "present",
    "asOf": null,
    "checkedAt": "2026-09-30",
    "maxAgeDays": 2,
    "surfaces": [
      "landing",
      "impact"
    ],
    "sourceUrl": null,
    "key": "partner_countries",
    "live": {
      "endpoint": "/impact",
      "path": "shelters.countries"
    }
  },
  "L-disbursed": {
    "id": "L-disbursed",
    "display": "Token Tails has sent {amount} to shelters",
    "appDisplay": null,
    "value": null,
    "unit": "USDC",
    "status": "live",
    "tense": "present",
    "asOf": null,
    "checkedAt": "2026-09-30",
    "maxAgeDays": 2,
    "surfaces": [
      "heist",
      "impact",
      "shelter-payouts"
    ],
    "sourceUrl": null,
    "chain": "arc",
    "live": {
      "endpoint": "/impact",
      "path": "money"
    }
  },
  "L-heists": {
    "id": "L-heists",
    "display": "{n} heists verified",
    "appDisplay": null,
    "value": null,
    "unit": "heists",
    "status": "live",
    "tense": "present",
    "asOf": null,
    "checkedAt": "2026-09-30",
    "maxAgeDays": 2,
    "surfaces": [
      "impact"
    ],
    "sourceUrl": null,
    "live": {
      "endpoint": "/impact",
      "path": "heists.verified"
    }
  },
  "L-match": {
    "id": "L-match",
    "display": "Gift match: {state}",
    "appDisplay": null,
    "value": null,
    "unit": null,
    "status": "live",
    "tense": "present",
    "asOf": null,
    "checkedAt": "2026-10-04",
    "maxAgeDays": 2,
    "surfaces": [
      "shelter-payouts"
    ],
    "sourceUrl": null,
    "key": "match_state",
    "live": {
      "endpoint": "/shelter/match/status",
      "path": "state"
    }
  },
  "L-players": {
    "id": "L-players",
    "display": "{n} players",
    "appDisplay": null,
    "value": null,
    "unit": "players",
    "status": "live",
    "tense": "present",
    "asOf": null,
    "checkedAt": "2026-09-30",
    "maxAgeDays": 2,
    "surfaces": [
      "impact"
    ],
    "sourceUrl": null,
    "live": {
      "endpoint": "/impact",
      "path": "players"
    }
  },
  "L-rail": {
    "id": "L-rail",
    "display": "Treat rail: {state}",
    "appDisplay": null,
    "value": null,
    "unit": null,
    "status": "live",
    "tense": "present",
    "asOf": null,
    "checkedAt": "2026-09-30",
    "maxAgeDays": 2,
    "surfaces": [
      "heist",
      "landing",
      "shelter-payouts"
    ],
    "sourceUrl": null,
    "key": "rail_state",
    "live": {
      "endpoint": "/shelter/donate/status",
      "path": "railState"
    }
  },
  "L-treats": {
    "id": "L-treats",
    "display": "Token Tails has sent {amount} in treats so far",
    "appDisplay": null,
    "value": null,
    "unit": "USDC",
    "status": "live",
    "tense": "present",
    "asOf": null,
    "checkedAt": "2026-09-30",
    "maxAgeDays": 2,
    "surfaces": [
      "heist",
      "impact"
    ],
    "sourceUrl": null,
    "chain": "arc",
    "live": {
      "endpoint": "/shelter/donate/status",
      "path": "communityTotalConfirmedWei"
    }
  }
};
