import Document, { Html, Head, Main, NextScript } from "next/document";
import { PRELOAD_FONT_FILES } from "../components/typography/fonts.generated";
import { isZoomLocked, skyForPath } from "../components/shared/skyScope";
import { THEME_COLOR } from "../design/tokens";

// Once the page has loaded, resolve the three brand faces the game roles use (the preloaded files,
// so this costs no extra request). The landing itself mostly renders Passion One 400 and Nunito;
// warming Passion One 900 and Bebas Neue here means /game's first canvas text never waits.
// document.fonts.load (never .check) is the only reliable signal (plan F4).
const WARM_BRAND_FONTS = `(function(){var f=document.fonts;if(!f||!f.load)return;function go(){['900 1em "Passion One"','400 1em "Bebas Neue"','700 1em "Nunito"'].forEach(function(d){f.load(d).catch(function(){})})}if(document.readyState==='complete')go();else window.addEventListener('load',go,{once:true})})();`;

// First paint is night on every route (plan G6): this inline rule paints before globals.css
// arrives, so no white or gray frame flashes between the native splash, the landing and /game.
// Only the background is global; cream ink and the dark colour scheme stay under [data-sky].
const FIRST_PAINT = `html,body{background-color:${THEME_COLOR}}html[data-sky]{color-scheme:dark}`;

/** Favicon (16, 32 and 48 frames), PNG icons for browsers that prefer them, and the iOS home icon. */
export const ICON_LINKS = [
  { rel: "icon", href: "/favicon.ico", sizes: "16x16 32x32 48x48" },
  { rel: "icon", href: "/icons/icon-32.png", type: "image/png", sizes: "32x32" },
  { rel: "icon", href: "/icons/icon-192.png", type: "image/png", sizes: "192x192" },
  { rel: "apple-touch-icon", href: "/icons/apple-touch-icon.png", sizes: "180x180" },
];

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    // ctx.pathname is the page pattern (`/game`, `/feed/[category]`), also during `next export`.
    const path = ctx.pathname || "/";
    return { ...initialProps, sky: skyForPath(path), zoomLocked: isZoomLocked(path) };
  }

  render() {
    const { sky, zoomLocked } = this.props;
    // The viewport meta lives in _app (next/head), so it follows client-side navigation:
    // zoom stays enabled everywhere except /game (WCAG 1.4.4, plan G6).
    return (
      <Html
        lang="en"
        data-sky={sky || undefined}
        data-zoom={zoomLocked ? "locked" : undefined}
      >
        <Head>
          <style
            id="tt-first-paint"
            dangerouslySetInnerHTML={{ __html: FIRST_PAINT }}
          />
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <meta
            name="apple-mobile-web-app-status-bar-style"
            content="black-translucent"
          />
          <meta name="mobile-web-app-capable" content="yes" />
          <meta name="theme-color" content={THEME_COLOR} />
          {/* The one icon set (plan G14): generated by scripts/build-icons.mjs. No page renders
              its own icon tags; scripts/check-meta.mjs fails if one does. */}
          {ICON_LINKS.map((link) => (
            <link key={link.href} {...link} />
          ))}
          <link rel="manifest" href="/manifest.webmanifest" />
          <meta name="format-detection" content="telephone=no" />
          {/* Self-hosted brand faces (plan F4): Passion One 900, Bebas Neue, Nunito, latin. */}
          {PRELOAD_FONT_FILES.map((href) => (
            <link
              key={href}
              rel="preload"
              href={href}
              as="font"
              type="font/woff2"
              crossOrigin="anonymous"
            />
          ))}
          <script dangerouslySetInnerHTML={{ __html: WARM_BRAND_FONTS }} />
          {/* Google Tag Manager is not injected here: it loads only after
              analytics consent, from components/GoogleTagManager.tsx. */}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
