/**
 * High-level solver scripts, one per campaign level (tools/solver.ts expands each into per-tick
 * inputs with an A* over the real sim). Cat 1 = index 0, cat 2 = index 1; both start active on cat 1.
 *
 * Steps: goto [x,y] (A* for the active cat, never spotted), collect (nearest-first sweep of the
 * listed coins or every coin reachable right now), swap, interact, meow, wait n ticks.
 */
import type { PlanStep } from './solver';

/** heist-01: tutorial room + Kibble Corp warehouse. */
export const HEIST_01_SCRIPT: PlanStep[] = [
  // Tutorial: cat 1 grabs the coin and holds plate a1; cat 2 slips through the door to plate a2.
  { collect: [[7, 7]], note: 'tutorial' },
  { goto: [1, 11], note: 'hold plate a1' },
  { swap: true },
  { goto: [13, 11], note: 'through the tutorial door to plate a2' },
  { swap: true },
  { goto: [14, 11], note: 'into the warehouse (past the checkpoint at the door)' },
  // Cat 1 loots the main hall on the way to the key-room plate.
  { collect: [[15, 9], [21, 12], [13, 4], [21, 5], [28, 6], [31, 9], [33, 10]], note: 'main hall' },
  { goto: [31, 8], note: 'hold the key-room plate' },
  // Cat 2 raids the key room.
  { swap: true },
  { goto: [26, 5], note: 'to the key-room door' },
  { collect: [[24, 1], [29, 3], [30, 2]], note: 'key room' },
  { goto: [36, 1], note: 'grab the key' },
  { goto: [26, 5], note: 'out of the key room' },
  // Lower hall and vault.
  { collect: [[25, 16], [21, 15], [20, 19], [14, 15], [14, 18]], note: 'lower hall' },
  { goto: [26, 16], note: 'to the vault door' },
  { interact: true },
  { collect: [[31, 15], [34, 16], [32, 18]], note: 'vault' },
  { goto: [35, 17], note: 'next to the crate' },
  { interact: true },
  { goto: [11, 1], note: 'cat 2 to the exit' },
  { swap: true },
  { collect: 'reachable', note: 'leftovers' },
  { goto: [12, 2], note: 'cat 1 to the exit' },
];

/** heist-02: lure the doorman west, then both cats slip down the east side into the crate room. */
export const HEIST_02_SCRIPT: PlanStep[] = [
  { swap: true },
  { goto: [21, 2], note: 'cat 2 to the checkpoint' },
  { goto: [21, 13], note: 'cat 2 waits on the east side, out of the doorman’s cone' },
  { swap: true },
  { collect: [[3, 4], [10, 2], [9, 3], [13, 1], [18, 1], [20, 3], [13, 5], [13, 7], [9, 9], [21, 7]], note: 'corridor and safe hall coins' },
  { goto: [10, 7], note: 'into meow range' },
  { meow: true },
  { goto: [21, 12], note: 'cat 1 runs to the east side' },
  { swap: true },
  { collect: [[18, 11], [15, 12], [14, 11]], note: 'risky coins while the doorman sniffs' },
  { goto: [15, 15], note: 'cat 2 through the doorway' },
  { goto: [9, 15], note: 'cat 2 waits on the exit' },
  { swap: true },
  { goto: [15, 15], note: 'cat 1 through the doorway' },
  { collect: [[18, 16], [19, 19]], note: 'crate room east' },
  { goto: [20, 19], note: 'next to the crate' },
  { interact: true },
  { collect: 'reachable', note: 'crate room west' },
  { goto: [8, 15], note: 'cat 1 to the exit' },
];

/** heist-03: leapfrog through doors A, D and F. */
export const HEIST_03_SCRIPT: PlanStep[] = [
  { collect: [[3, 3], [5, 6], [4, 9]], note: 'lab coins' },
  { goto: [1, 6], note: 'cat 1 holds plate a1' },
  { swap: true },
  { goto: [9, 3], note: 'cat 2 through A onto plate a2' },
  { swap: true },
  { goto: [8, 1], note: 'cat 1 through A (checkpoint just past the door)' },
  { collect: [[11, 1], [16, 1], [9, 5], [18, 5], [13, 7], [10, 9], [16, 9]], note: 'R2 coins' },
  { goto: [18, 8], note: 'cat 1 holds plate d1' },
  { swap: true },
  { goto: [22, 2], note: 'cat 2 through D onto plate d2' },
  { swap: true },
  { goto: [23, 9], note: 'cat 1 through D (checkpoint just past the door)' },
  { collect: [[23, 7], [24, 6]], note: 'R3 coins' },
  { collect: [[27, 7]], note: 'R3 coins' },
  { collect: [[26, 1], [23, 3]], note: 'R3 coins' },
  { goto: [21, 9], note: 'cat 1 holds plate f1' },
  { swap: true },
  { goto: [22, 12], note: 'cat 2 through F onto plate f2' },
  { swap: true },
  { goto: [25, 11], note: 'cat 1 through F' },
  { collect: 'reachable', note: 'alcove coins' },
  { goto: [27, 12], note: 'next to the crate' },
  { interact: true },
  { goto: [23, 13], note: 'cat 1 to the exit' },
  { swap: true },
  { goto: [22, 13], note: 'cat 2 to the exit' },
];

/** heist-04: office key behind plate door G, vault between laps of the fast dog. */
export const HEIST_04_SCRIPT: PlanStep[] = [
  { collect: [[3, 16]], note: 'start room' },
  { collect: [[9, 13], [8, 4], [9, 9], [9, 1], [11, 5], [18, 1], [10, 4]], note: 'west and north lanes' },
  { goto: [28, 1], note: 'cat 1 to the checkpoint' },
  { goto: [28, 6], note: 'cat 1 waits by the office' },
  { swap: true },
  { goto: [8, 14], note: 'cat 2 into the hall' },
  { goto: [28, 1], note: 'cat 2 to the checkpoint' },
  { goto: [28, 5], note: 'cat 2 waits at the office door' },
  { swap: true },
  { goto: [27, 8], note: 'cat 1 holds plate g1' },
  { swap: true },
  { goto: [31, 5], note: 'cat 2 into the office' },
  { swap: true },
  { goto: [28, 6], note: 'cat 1 steps off' },
  { swap: true },
  { collect: [[31, 3], [33, 3], [31, 6]], note: 'office coins' },
  { goto: [33, 2], note: 'grab the key' },
  { goto: [30, 5], note: 'cat 2 waits inside the office door' },
  { swap: true },
  { goto: [27, 8], note: 'cat 1 holds plate g1 again' },
  { swap: true },
  { goto: [28, 4], note: 'cat 2 out of the office' },
  { swap: true },
  { goto: [28, 6], note: 'cat 1 steps off again' },
  { swap: true },
  { collect: [[25, 5], [26, 10], [27, 13], [19, 13]], note: 'east and south lanes' },
  { goto: [17, 13], note: 'to the vault door' },
  { interact: true },
  { collect: [[15, 7], [19, 7], [13, 10], [21, 10], [14, 11]], note: 'vault coins' },
  { goto: [20, 11], note: 'next to the crate' },
  { interact: true },
  { goto: [17, 13], note: 'out of the vault' },
  { collect: [[11, 17], [16, 18], [21, 17]], note: 'south lane' },
  { goto: [1, 13], note: 'cat 2 to the exit' },
  { swap: true },
  { collect: 'reachable', note: 'leftovers' },
  { goto: [1, 14], note: 'cat 1 to the exit' },
];

/** heist-05: cross the sentry yard, leapfrog door H into the compound. */
export const HEIST_05_SCRIPT: PlanStep[] = [
  { collect: 'reachable', note: 'yard coins (cat 1)' },
  { goto: [25, 8], note: 'cat 1 holds plate h1' },
  { swap: true },
  { goto: [12, 14], note: 'cat 2 into the yard (past the checkpoint)' },
  { goto: [22, 5], note: 'cat 2 through H' },
  { goto: [21, 3], note: 'cat 2 holds plate h2' },
  { swap: true },
  { goto: [22, 5], note: 'cat 1 through H' },
  { collect: 'reachable', note: 'compound coins' },
  { goto: [24, 1], note: 'next to the crate' },
  { interact: true },
  { goto: [22, 4], note: 'cat 1 to the exit' },
  { swap: true },
  { goto: [21, 4], note: 'cat 2 to the exit' },
];

/** heist-06: three paced corridors, then leapfrog door L from the plate niche. */
export const HEIST_06_SCRIPT: PlanStep[] = [
  { collect: [[1, 4], [12, 3], [9, 1], [18, 3], [21, 1], [24, 3]], note: 'corridor 1' },
  { goto: [28, 4], note: 'cat 1 to the checkpoint' },
  { collect: [[28, 5], [22, 7], [19, 9], [16, 7]], note: 'corridor 2 east' },
  { goto: [13, 9], note: 'cat 1 to the niche checkpoint' },
  { collect: [[10, 7], [7, 9], [2, 9]], note: 'corridor 2 west' },
  { collect: [[7, 11], [9, 13], [12, 11]], note: 'corridor 3' },
  { goto: [15, 13], note: 'cat 1 holds plate l1' },
  { swap: true },
  { goto: [28, 4], note: 'cat 2 through corridor 1' },
  { goto: [13, 9], note: 'cat 2 through corridor 2' },
  { goto: [28, 11], note: 'cat 2 through L onto plate l2' },
  { swap: true },
  { collect: [[18, 11], [25, 11]], note: 'cat 1 through L' },
  { collect: 'reachable', note: 'crate room' },
  { goto: [26, 13], note: 'next to the crate' },
  { interact: true },
  { goto: [25, 14], note: 'cat 1 to the exit' },
  { swap: true },
  { goto: [26, 14], note: 'cat 2 to the exit' },
];

/** heist-07: north and south wings open each other's doors in turn. */
export const HEIST_07_SCRIPT: PlanStep[] = [
  { collect: [[6, 1], [4, 3], [7, 5]], note: 'N1 coins' },
  { goto: [9, 3], note: 'cat 1 waits at door P' },
  { swap: true },
  { collect: [[4, 9], [7, 12], [3, 13]], note: 'S1 coins' },
  { goto: [5, 11], note: 'cat 2 holds p' },
  { swap: true },
  { goto: [11, 5], note: 'cat 1 through P (checkpoint just past the door)' },
  { collect: [[12, 5], [15, 3]], note: 'N2 coins' },
  { goto: [14, 4], note: 'cat 1 holds t' },
  { swap: true },
  { goto: [11, 11], note: 'cat 2 through T' },
  { swap: true },
  { goto: [11, 5], note: 'cat 1 steps off t' },
  { swap: true },
  { collect: [[13, 13], [17, 9]], note: 'S2 coins' },
  { goto: [16, 10], note: 'cat 2 holds q' },
  { swap: true },
  { goto: [21, 2], note: 'cat 1 through Q' },
  { collect: [[24, 1], [27, 3]], note: 'N3 coins' },
  { goto: [24, 2], note: 'cat 1 holds u' },
  { swap: true },
  { goto: [21, 13], note: 'cat 2 through U (checkpoint just past the door)' },
  { collect: [[22, 9], [25, 11], [28, 13]], note: 'S3 coins' },
  { goto: [26, 12], note: 'cat 2 holds s' },
  { swap: true },
  { goto: [31, 4], note: 'cat 1 through S' },
  { collect: [[31, 1], [32, 3]], note: 'east room north' },
  { goto: [35, 2], note: 'cat 1 holds w' },
  { swap: true },
  { goto: [31, 10], note: 'cat 2 through W' },
  { collect: 'reachable', note: 'east room' },
  { goto: [33, 7], note: 'next to the crate' },
  { interact: true },
  { goto: [32, 5], note: 'cat 2 to the exit' },
  { swap: true },
  { goto: [33, 5], note: 'cat 1 to the exit' },
];

/** heist-08: the finale. */
export const HEIST_08_SCRIPT: PlanStep[] = [
  { collect: [[3, 20], [8, 25]], note: 'lobby coins' },
  { goto: [7, 21], note: 'cat 1 holds plate a1' },
  { swap: true },
  { goto: [12, 22], note: 'cat 2 through A onto plate a2' },
  { swap: true },
  { goto: [11, 25], note: 'cat 1 through A (checkpoint just past the door)' },
  { swap: true },
  { goto: [30, 12], note: 'cat 2 waits by door F' },
  { swap: true },
  { collect: [[12, 19], [12, 15]], note: 'hall west coins' },
  { goto: [13, 10], note: 'cat 1 into the yard (checkpoint under the gap)' },
  { collect: [[14, 8], [13, 2], [9, 5], [6, 2], [2, 5], [5, 10]], note: 'yard coins' },
  { goto: [2, 9], note: 'cat 1 holds plate f' },
  { swap: true },
  { goto: [27, 5], note: 'cat 2 through F (checkpoint)' },
  { collect: [[27, 7]], note: 'column coin' },
  { collect: [[30, 3], [32, 2], [33, 4], [36, 2]], note: 'corridor coins' },
  { goto: [38, 3], note: 'into the key room' },
  { collect: [[36, 5], [38, 9]], note: 'key room coins' },
  { goto: [37, 8], note: 'grab the key' },
  { goto: [27, 5], note: 'back along the corridor' },
  { goto: [30, 12], note: 'cat 2 back through F' },
  { collect: [[29, 14], [29, 20]], note: 'hall east coins' },
  { goto: [30, 20], note: 'cat 2 waits east of the vault' },
  { swap: true },
  { goto: [13, 10], note: 'cat 1 out of the yard' },
  { collect: [[20, 13]], note: 'hall north coin' },
  { goto: [15, 19], note: 'cat 1 waits near meow range' },
  {
    try: [
      { goto: [15, 21], note: 'cat 1 into meow range' },
      { meow: true },
      { goto: [13, 10], note: 'cat 1 runs back to the yard' },
      { swap: true },
      { goto: [20, 21], note: 'cat 2 to the vault door' },
      { interact: true },
    ],
    waitUpTo: 600,
    note: 'first lure',
  },
  { collect: [[21, 18], [19, 19], [18, 16]], note: 'vault coins' },
  { goto: [22, 17], note: 'next to the crate' },
  { interact: true },
  { goto: [18, 17], note: 'cat 2 waits inside the vault' },
  { swap: true },
  { goto: [15, 19], note: 'cat 1 waits near meow range' },
  {
    try: [
      { goto: [15, 21], note: 'cat 1 back in meow range' },
      { meow: true },
      { goto: [13, 10], note: 'cat 1 runs back to the yard' },
      { swap: true },
      { collect: [[16, 24], [25, 24], [29, 25]], note: 'cat 2 out of the vault: hall south coins' },
      { goto: [11, 25], note: 'cat 2 waits by the lobby door' },
    ],
    waitUpTo: 600,
    note: 'second lure',
  },
  { swap: true },
  {
    try: [
      { goto: [12, 22], note: 'cat 1 holds plate a2' },
      { swap: true },
      { goto: [7, 21], note: 'cat 2 through A onto plate a1' },
      { swap: true },
      { goto: [3, 24], note: 'cat 1 through A to the exit' },
    ],
    waitUpTo: 600,
    note: 'leapfrog out',
  },
  { swap: true },
  { goto: [2, 24], note: 'cat 2 to the exit' },
];

/** Scripts per level id. Add an entry (and tools/levels/<id>.mjs) to have `npm run solve` plan it. */
export const LEVEL_SCRIPTS: Record<string, PlanStep[]> = {
  'heist-01': HEIST_01_SCRIPT,
  'heist-02': HEIST_02_SCRIPT,
  'heist-03': HEIST_03_SCRIPT,
  'heist-04': HEIST_04_SCRIPT,
  'heist-05': HEIST_05_SCRIPT,
  'heist-06': HEIST_06_SCRIPT,
  'heist-07': HEIST_07_SCRIPT,
  'heist-08': HEIST_08_SCRIPT,
};
