// `fund facts absorb`: moves FACTS.md edits back into facts.json.
//
// `fund refresh --write` still edits FACTS.md in place (value, date and status of probed rows).
// Without this step the next `fund facts build --check` would report drift. Only those three cells
// are absorbed (Value -> value, Date -> checkedAt, Status -> status); a changed Fact or Source cell is
// reported so a person edits facts.json by hand.

import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { readFactRows } from '../facts-refresh.mjs';
import { REGISTRY, TARGETS, loadRegistry, mdStatus, mdValue } from './build.mjs';
import { formatRegistry } from './format.mjs';
import { family } from './schema.mjs';

/** "1,218,700" -> 1218700 when the registry value is a number; anything else stays a string. */
function parseMdValue(cell, previous) {
  if (typeof previous === 'number') {
    const n = Number(cell.replace(/,/g, ''));
    if (Number.isFinite(n) && /^[\d,]+(?:\.\d+)?$/.test(cell)) return n;
  }
  return cell;
}

export function absorbFactsMd({ root, write = true } = {}) {
  const mdPath = join(root, TARGETS.factsMd);
  if (!existsSync(mdPath)) return { patched: [], manual: [], wrote: false };
  const rows = readFactRows(mdPath);
  const registry = loadRegistry(root);
  const patched = [];
  const manual = [];
  for (const f of registry.facts) {
    if (family(f.id) !== 'F') continue;
    const row = rows.get(f.id);
    if (!row) { manual.push(`${f.id}: missing from FACTS.md (it is regenerated by fund facts build)`); continue; }
    const changes = [];
    if (row.value !== mdValue(f.value)) { const v = parseMdValue(row.value, f.value); changes.push(['value', f.value, v]); f.value = v; }
    if (row.date !== f.checkedAt) { changes.push(['checkedAt', f.checkedAt, row.date]); f.checkedAt = row.date; }
    if (row.status !== mdStatus(f.status)) { changes.push(['status', f.status, row.status]); f.status = row.status; }
    if (row.label !== f.claim) manual.push(`${f.id}: the Fact cell differs; copy it into "claim" in ${REGISTRY} by hand`);
    if (row.source !== f.source) manual.push(`${f.id}: the Source cell differs; copy it into "source" in ${REGISTRY} by hand`);
    if (changes.length) patched.push({ id: f.id, changes });
  }
  for (const id of rows.keys()) if (!registry.facts.some((f) => f.id === id)) manual.push(`${id}: in FACTS.md but not in ${REGISTRY}; add the entry there`);
  const wrote = write && patched.length > 0;
  if (wrote) writeFileSync(join(root, REGISTRY), formatRegistry(registry));
  return { patched, manual, wrote, registry };
}
