import { Abilities } from "@/components/catbassadors/objects/Abilities";
import { ICatAnimationKeysMap } from "@/components/catbassadors/objects/Catbassador";
import { CatAbilityType } from "@/models/cats";

export interface IPlayer {
  sprite: Phaser.Physics.Arcade.Sprite;
  animationKeys: ICatAnimationKeysMap;
  cursors: Phaser.Types.Input.Keyboard.CursorKeys;
  keys: {
    up: Phaser.Input.Keyboard.Key;
    upW: Phaser.Input.Keyboard.Key;
    left: Phaser.Input.Keyboard.Key;
    right: Phaser.Input.Keyboard.Key;
    dash: Phaser.Input.Keyboard.Key;
    knockback: Phaser.Input.Keyboard.Key;
  };
  isMobileJumping: boolean;
  isMobileLeft: boolean;
  isMobileRight: boolean;
  isMobileDash: boolean;
  isMobileknockbackSpell: boolean;
  isDashing: boolean;
  walkSpeed: number;
  jumpSpeed: number;
  wallSlideSpeed: number;
  disableLeftMovement: boolean;
  disableRightMovement: boolean;
  justJumped: boolean;
  isSliding: boolean;
  maxJumpSpeed: number;
  coyoteTime: number;
  wallTouchTime: number;
  lastWallTouched: "left" | "right" | null;
  jumpTimer: number;
  dashTime: number;
  dashCooldown: number;
  dashSpeed: number;
  isJumping: boolean;
  wallJumpCount: number;
  scene: Phaser.Scene;
  isHit: boolean;
  isDeath: boolean;
  isInvulnerable: boolean;
  hasKey: boolean;
  abilities: Abilities;
  type: CatAbilityType;
  isOnIcyTile: boolean;
  isAutoRunMode: boolean;
  isSitting: boolean;
}
