import { CatAbilitySkill, CatAbilityType } from "@/models/cats";

export const cats = [
    {
        name: 'Catastrophe',
        resqueStory:
            'A wizard cat tries a spell to summon fish, but ends up with a rain of squeaky toys instead. The magical mishaps continue!',
        ability: CatAbilitySkill.AQUAWHISKER,
        type: CatAbilityType.WATER,
        tier: 'MYTHICAL',
        collectionType: 'WIZARDIA',
        status: {
            EAT: 0,
            PLAY: 0,
        },
        origin: 'GREY',
        code: '202406087715344990',
        price: 222,
        lives: 9,
        spriteImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/GREY/hat-wizard-blue.png',
        catImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/GREY/hat-wizard-blue/JUMPING.gif',
        cardImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/cards/WIZARDIA/catastrophe.png',
    },
    {
        name: 'Clawdius Caesar',
        resqueStory:
            'A wizard cat’s potion for invisibility works too well, and now he’s chasing his own tail in confusion.',
        ability: CatAbilitySkill.WHISKERFLAME,
        type: CatAbilityType.FIRE,
        tier: 'MYTHICAL',
        collectionType: 'WIZARDIA',
        status: {
            EAT: 0,
            PLAY: 0,
        },
        origin: 'YELLOW',
        code: '202406087337083445',
        price: 555,
        lives: 9,
        spriteImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/YELLOW/hat-wizard-blue.png',
        catImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/YELLOW/hat-wizard-blue/JUMPING.gif',
        cardImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/cards/WIZARDIA/clawdius-caesar.png',
    },
    {
        name: 'Purrcules',
        resqueStory:
            'A wizard cat casts a spell for nine lives but ends up with nine different lives and nine bowls of milk to manage.',
        ability: CatAbilitySkill.TAILWIND,
        type: CatAbilityType.WIND,
        tier: 'MYTHICAL',
        collectionType: 'WIZARDIA',
        status: {
            EAT: 0,
            PLAY: 0,
        },
        origin: 'SIAMESE',
        code: '202406082965982034',
        price: 420,
        lives: 9,
        spriteImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/SIAMESE/hat-cylinder-black.png',
        catImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/SIAMESE/hat-cylinder-black/JUMPING.gif',
        cardImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/cards/WIZARDIA/purrcules.png',
    },
    {
        name: 'Sir Purrs-a-Lot',
        resqueStory: 'A wizard cat’s spell book gets swapped with a cookbook, resulting in enchanted tuna casseroles.',
        ability: CatAbilitySkill.PURRSTORM,
        type: CatAbilityType.WIND,
        tier: 'MYTHICAL',
        collectionType: 'WIZARDIA',
        status: {
            EAT: 0,
            PLAY: 0,
        },
        origin: 'BLACK',
        code: '202406084842622463',
        price: 333,
        lives: 9,
        spriteImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/BLACK/hat-cylinder-black.png',
        catImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/BLACK/hat-cylinder-black/JUMPING.gif',
        cardImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/cards/WIZARDIA/sir-purrs-a-lot.png',
    },
    {
        name: 'Snoop-Cat',
        resqueStory:
            'A wizard cat’s broomstick flying lessons turn into a high-speed chase after a squirrel in mid-air.',
        ability: CatAbilitySkill.WHISKERFLAME,
        type: CatAbilityType.FIRE,
        tier: 'MYTHICAL',
        collectionType: 'WIZARDIA',
        status: {
            EAT: 0,
            PLAY: 0,
        },
        origin: 'BLACK',
        code: '202406081492289275',
        price: 690,
        lives: 9,
        spriteImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/BLACK/hat-musketeer-red.png',
        catImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/BLACK/hat-musketeer-red/JUMPING.gif',
        cardImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/cards/WIZARDIA/meowzilla.png',
    },
    {
        name: 'Purrlock Holmes',
        resqueStory:
            'A charming cat purrs so soothingly that even the grumpiest dog falls asleep, dreaming of chasing butterflies.',
        ability: CatAbilitySkill.AQUAWHISKER,
        type: CatAbilityType.WATER,
        tier: 'MYTHICAL',
        collectionType: 'LOVETAP',
        status: {
            EAT: 0,
            PLAY: 0,
        },
        origin: 'BLACK',
        code: '202406080011546784',
        price: 111,
        lives: 9,
        spriteImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/BLACK/hearted-red.png',
        catImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/BLACK/hearted-red/JUMPING.gif',
        cardImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/cards/LOVETAP/purrlock-holmes.png',
    },
    {
        name: 'Purrito',
        resqueStory:
            'A charming cat’s whisker wiggles are so enchanting that they hypnotize the neighborhood mice into bringing him cheese.',
        ability: CatAbilitySkill.TAILWIND,
        type: CatAbilityType.STORM,
        tier: 'MYTHICAL',
        collectionType: 'LOVETAP',
        status: {
            EAT: 0,
            PLAY: 0,
        },
        origin: 'YELLOW',
        code: '202406085721204017',
        price: 50,
        lives: 9,
        spriteImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/YELLOW/hearted-red.png',
        catImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/YELLOW/hearted-red/JUMPING.gif',
        cardImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/cards/LOVETAP/purrito.png',
    },
    {
        name: 'Cleocatra',
        resqueStory:
            'A charming cat’s tail swishes create rainbows that make everyone smile, even on the rainiest of days.',
        ability: CatAbilitySkill.AQUAWHISKER,
        type: CatAbilityType.WATER,
        tier: 'MYTHICAL',
        collectionType: 'LOVETAP',
        status: {
            EAT: 0,
            PLAY: 0,
        },
        origin: 'PINKIE',
        code: '202406084023598528',
        price: 69,
        lives: 9,
        spriteImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/PINKIE/hearted-red.png',
        catImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/PINKIE/hearted-red/JUMPING.gif',
        cardImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/cards/LOVETAP/cleocatra.png',
    },
    {
        name: 'Purrfecto',
        resqueStory:
            'An angel cupid cat spreads love so pure that even the fiercest tomcats become gentle cuddle buddies under its spell."',
        ability: CatAbilitySkill.TAILWIND,
        type: CatAbilityType.WIND,
        tier: 'MYTHICAL',
        collectionType: 'LOVETAP',
        status: {
            EAT: 0,
            PLAY: 0,
        },
        origin: 'GREY',
        code: '202406084458739063',
        price: 777,
        lives: 9,
        spriteImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/GREY/wing-black.png',
        catImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/GREY/wing-black/JUMPING.gif',
        cardImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/cards/LOVETAP/purrfecto.png',
    },
    {
        name: 'Clawdiator',
        resqueStory:
            'A demon cupid cat’s mischievous love arrows cause hilarious mix-ups, like a dog falling head over paws for the mailman',
        ability: CatAbilitySkill.PURRSTORM,
        type: CatAbilityType.ELECTRIC,
        tier: 'MYTHICAL',
        collectionType: 'LOVETAP',
        status: {
            EAT: 0,
            PLAY: 0,
        },
        origin: 'SIAMESE',
        code: '202406088317094277',
        price: 1000,
        lives: 9,
        spriteImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/SIAMESE/wing-white.png',
        catImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/SIAMESE/wing-white/JUMPING.gif',
        cardImg: 'https://tokentails-nfts.fra1.cdn.digitaloceanspaces.com/assets/cards/LOVETAP/clawdiator.png',
    },
];
