// node --test scripts/__tests__/
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { afterEach, beforeEach, describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';
import { GENERATED_MARKER, header, relativeImports, sync } from '../sync-contracts.mjs';

const SCRIPT = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'sync-contracts.mjs');
const REPO = resolve(dirname(SCRIPT), '..');

let root;

function write(path, content) {
    mkdirSync(dirname(join(root, path)), { recursive: true });
    writeFileSync(join(root, path), content);
}

const read = path => readFileSync(join(root, path), 'utf8');

function fixture(files = { 'a.ts': ['one', 'two'], 'b.ts': ['one'] }) {
    write(
        'shared/manifest.json',
        JSON.stringify({ targets: { one: 'pkg-one/contracts', two: 'pkg-two/src/contracts' }, files })
    );
    write('shared/a.ts', "export const A = 'a';\n");
    write('shared/b.ts', "import { A } from './a';\nexport const B = A + 'b';\n");
}

function runCli(args) {
    try {
        const stdout = execFileSync(process.execPath, [SCRIPT, '--root', root, ...args], { encoding: 'utf8', stdio: 'pipe' });
        return { code: 0, stdout };
    } catch (error) {
        return { code: error.status, stdout: `${error.stdout}${error.stderr}` };
    }
}

beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'sync-contracts-'));
});

afterEach(() => {
    rmSync(root, { recursive: true, force: true });
});

describe('sync-contracts', () => {
    it('writes each file to its targets with the GENERATED header', () => {
        fixture();
        const result = sync({ root });
        assert.equal(result.ok, true);
        assert.deepEqual(result.written.sort(), ['pkg-one/contracts/a.ts', 'pkg-one/contracts/b.ts', 'pkg-two/src/contracts/a.ts']);
        const copy = read('pkg-two/src/contracts/a.ts');
        assert.ok(copy.startsWith(header('a.ts')));
        assert.ok(copy.includes(GENERATED_MARKER));
        assert.ok(copy.endsWith("export const A = 'a';\n"));
        assert.match(copy.split('\n')[0], /^\/\/ GENERATED by scripts\/sync-contracts\.mjs from shared\/a\.ts/);
    });

    it('is idempotent and leaves unchanged copies untouched', () => {
        fixture();
        sync({ root });
        const before = statSync(join(root, 'pkg-one/contracts/a.ts')).mtimeMs;
        const second = sync({ root });
        assert.deepEqual(second.written, []);
        assert.deepEqual(second.removed, []);
        assert.equal(statSync(join(root, 'pkg-one/contracts/a.ts')).mtimeMs, before);
        assert.equal(sync({ root, check: true }).ok, true);
    });

    it('rewrites only the file whose source changed', () => {
        fixture();
        sync({ root });
        write('shared/b.ts', "import { A } from './a';\nexport const B = A + 'bb';\n");
        const result = sync({ root });
        assert.deepEqual(result.written, ['pkg-one/contracts/b.ts']);
    });

    it('--check reports drift from an edited copy, a missing copy and a stale source, and writes nothing', () => {
        fixture();
        sync({ root });
        write('pkg-one/contracts/a.ts', `${header('a.ts')}export const A = 'hand edited';\n`);
        rmSync(join(root, 'pkg-two/src/contracts/a.ts'));
        const result = sync({ root, check: true });
        assert.equal(result.ok, false);
        assert.deepEqual(result.stale.sort(), ['pkg-one/contracts/a.ts', 'pkg-two/src/contracts/a.ts']);
        assert.equal(existsSync(join(root, 'pkg-two/src/contracts/a.ts')), false);
        assert.match(read('pkg-one/contracts/a.ts'), /hand edited/);
    });

    it('exits 1 on drift and 0 when clean from the command line', () => {
        fixture();
        assert.equal(runCli(['--check']).code, 1);
        assert.equal(runCli([]).code, 0);
        const clean = runCli(['--check']);
        assert.equal(clean.code, 0);
        assert.match(clean.stdout, /up to date/);
    });

    it('flags and removes generated files the manifest no longer produces, but never hand-written ones', () => {
        fixture();
        sync({ root });
        write('pkg-one/contracts/handwritten.ts', 'export const keep = 1;\n');
        write('shared/manifest.json', JSON.stringify({ targets: { one: 'pkg-one/contracts', two: 'pkg-two/src/contracts' }, files: { 'a.ts': ['one', 'two'] } }));
        rmSync(join(root, 'shared/b.ts'));
        const check = sync({ root, check: true });
        assert.deepEqual(check.stale, ['pkg-one/contracts/b.ts']);
        const result = sync({ root });
        assert.deepEqual(result.removed, ['pkg-one/contracts/b.ts']);
        assert.equal(existsSync(join(root, 'pkg-one/contracts/handwritten.ts')), true);
    });

    it('never treats another run\'s in-flight temp file as an orphan', () => {
        fixture();
        sync({ root });
        const temp = 'pkg-one/contracts/a.ts.99999.tmp';
        write(temp, header('a.ts') + "export const A = 'a';\n");
        const checked = sync({ root, check: true });
        assert.equal(checked.ok, true);
        assert.deepEqual(checked.stale, []);
        sync({ root });
        assert.equal(existsSync(join(root, temp)), true);
    });

    it('skips listed files that do not exist yet as pending', () => {
        fixture({ 'a.ts': ['one'], 'b.ts': ['one'], 'later.ts': ['two'] });
        const result = sync({ root });
        assert.equal(result.ok, true);
        assert.deepEqual(result.pending, ['later.ts']);
        assert.equal(sync({ root, check: true }).ok, true);
    });

    it('fails when a shared file is not in the manifest', () => {
        fixture();
        write('shared/stray.ts', 'export {};\n');
        const result = sync({ root });
        assert.equal(result.ok, false);
        assert.match(result.errors.join('\n'), /shared\/stray\.ts is not listed/);
        assert.deepEqual(result.written, []);
    });

    it('fails when a file imports a shared file that is not copied to the same target', () => {
        fixture({ 'a.ts': ['one'], 'b.ts': ['one', 'two'] });
        const result = sync({ root });
        assert.equal(result.ok, false);
        assert.match(result.errors.join('\n'), /b\.ts imports a\.ts, which is not copied to "two"/);
    });

    it('rejects unknown targets and paths outside shared/', () => {
        fixture({ 'a.ts': ['nope'], 'b.ts': ['one'] });
        assert.throws(() => sync({ root }), /unknown target "nope"/);
        fixture({ '../a.ts': ['one'] });
        assert.throws(() => sync({ root }), /must be a path inside shared/);
    });

    it('resolves relative imports from nested files', () => {
        assert.deepEqual(relativeImports('__tests__/x.test.ts', "import { A } from '../a';\nimport * as B from '../b.ts';"), ['a.ts', 'b.ts']);
        assert.deepEqual(relativeImports('c.ts', "export { A } from './a';\nimport x from 'jest';"), ['a.ts']);
    });

    it('reports the real repo as in sync', () => {
        assert.equal(sync({ root: REPO, check: true }).ok, true);
    });
});

it('CLI exits 2 with usage on a missing --root value or an unknown argument', () => {
    for (const args of [['--root'], ['--root', '--check'], ['--bogus']]) {
        let status = 0;
        let stderr = '';
        try {
            execFileSync(process.execPath, [SCRIPT, ...args], { encoding: 'utf8', stdio: 'pipe' });
        } catch (error) {
            status = error.status;
            stderr = `${error.stderr}`;
        }
        assert.equal(status, 2, args.join(' '));
        assert.match(stderr, /usage: node scripts\/sync-contracts\.mjs/);
    }
});
