// Track A pipeline — "build once, submit many" as one `fund run`.
//
//   source → extract → draft (sibling copy or AI) → check → build (a:build) → deploy (HUMAN signs)
//   → record (HUMAN: a:record) → verify-deploy (a:verify, optional: only with an RPC env var)
//   → submission (a:submission) → check-submission → review → revise → human-read → ready
//   → submit (HUMAN pastes submission.md) → record-submission
//
// Every done() reads files only (deployments.json, build-evidence.md, submission.md, call.md).
// Nothing here signs, broadcasts or submits: deploy, record and submit are human steps.

import { existsSync, statSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  readEvidence, loadDeployments, loadChains, networkInfo, appChains, mainnetRequired, trackAApps, copyDraftFrom, renderSubmission, paths,
} from './track.mjs';

const EVIDENCE_MAX_DAYS = 7; // same limit as the A:build-evidence check
const PLACEHOLDER_ROW = /replace with|verbatim quote|^\s*$/i;

// ---------- invoke a fund command, capture its output into a one-line message ----------

async function call(ctx, argv) {
  const lines = [];
  const orig = { log: console.log, error: console.error, warn: console.warn };
  const grab = (...a) => lines.push(a.map(String).join(' '));
  console.log = grab; console.error = grab; console.warn = grab;
  let code;
  try { code = await ctx.invoke(argv); } catch (e) { lines.push(`error: ${e.message}`); code = 1; } finally { Object.assign(console, orig); }
  const out = lines.join('\n').split('\n').map((l) => l.trim()).filter(Boolean);
  return { code: code ?? 0, lines: out };
}

function outcome(res, argv, okText) {
  const cmd = `fund ${argv.join(' ')}`;
  if (res.code === 0) return { ok: true, message: okText || `${cmd} ok` };
  const bad = res.lines.filter((l) => /^(✗|!|error|usage|no |set |fix )/i.test(l)).slice(0, 3);
  const nx = res.lines.filter((l) => l.startsWith('next:')).pop();
  return { ok: false, message: `${cmd} exited ${res.code}: ${(bad.length ? bad : res.lines.slice(-1)).join('; ')}${nx ? ` — ${nx}` : ''}` };
}

// ---------- file detectors ----------

const mtime = (f) => (existsSync(f) ? statSync(f).mtimeMs : 0);

function realCriteria(app) {
  return (app?.criteria || []).filter((c) => c.name && !PLACEHOLDER_ROW.test(c.quote || '') && !PLACEHOLDER_ROW.test(c.name));
}

function draftComplete(app) {
  const secs = app?.sections || [];
  return secs.length > 0 && secs.every((s) => s.chars > 0 && !/^(TODO|TBD)\b/i.test(s.text));
}

/** The deployments that satisfy this app: mainnet on its chains when mainnet_required, else any on its chains. */
function deployState(app) {
  const chains = appChains(app);
  const req = mainnetRequired(app);
  const network = req === true ? 'mainnet' : 'testnet';
  const chain = chains[0] || '<chain>';
  let list = [];
  let error = '';
  try { list = loadDeployments(); } catch (e) { error = e.message; }
  const rel = list.filter((d) => !chains.length || chains.includes(d.chain));
  const want = req === true ? rel.filter((d) => d.network === 'mainnet') : rel;
  return { chains, req, network, chain, want, error, deployCmd: `fund a:deploy ${chain} ${network}` };
}

function deployProblem(s) {
  if (s.error) return s.error;
  if (s.req === 'invalid') return 'mainnet_required in call.md is not true or false — fix it first';
  if (!s.chains.length) return 'no chain: in call.md — set it to a key in tracks/a-build/chains.json';
  return '';
}

function evidenceState(app) {
  const ev = readEvidence(app);
  if (!ev) return { done: false, reason: 'no build-evidence.md yet' };
  if (String(ev.passed) !== 'true') return { done: false, reason: `tests failing (${ev.tests_failed} failed) — fix them in ${paths.project()}` };
  if (ev.ageDays > EVIDENCE_MAX_DAYS) return { done: false, reason: `build-evidence.md is ${ev.ageDays.toFixed(1)} days old (max ${EVIDENCE_MAX_DAYS})` };
  const tree = ev.tree && ev.tree !== 'clean' ? ` — built from ${ev.tree}: commit and push ShelterSplit before ready` : '';
  return { done: true, reason: `${ev.tests_passed}/${ev.tests_total} tests pass, ${ev.ageDays.toFixed(1)}d old${tree}`, ev };
}

// Content, not mtimes: submission.md must equal what a:submission would render now (the timestamp
// line aside), so a verified deployment, a new build or a draft edit all make it stale at once.
const normSub = (t) => String(t).replace(/_Generated \S+ by/, '_Generated by').replace(/\r\n?/g, '\n').trim();
function submissionState(ctx) {
  const sub = join(ctx.dir, 'submission.md');
  if (!existsSync(sub)) return { done: false, reason: 'no submission.md yet' };
  const have = normSub(readFileSync(sub, 'utf8'));
  let fresh;
  try { fresh = [false, true].some((keepCites) => normSub(renderSubmission(ctx.app, { keepCites }).text) === have); } catch (e) { return { done: false, reason: `cannot render the submission: ${e.message}` }; }
  if (!fresh) return { done: false, reason: 'submission.md is out of date (draft, deployments or build evidence changed)' };
  // the A:submission check compares file times; keep both views in agreement
  const inputs = { 'draft.md': mtime(join(ctx.dir, 'draft.md')), 'deployments.json': mtime(paths.deployments()), 'build-evidence.md': mtime(join(ctx.dir, 'build-evidence.md')) };
  const older = Object.entries(inputs).filter(([, t]) => t && mtime(sub) + 1000 < t).map(([k]) => k);
  if (older.length) return { done: false, reason: `submission.md is older than ${older.join(', ')} (A:submission check)` };
  return { done: true, reason: 'submission.md matches draft, profile, deployments and build evidence' };
}

/** A sibling Track A application whose draft is complete (preferring --from, then the same frame, then the newest). */
function pickSibling(ctx) {
  if (ctx.flags?.['no-copy']) return null;
  const from = typeof ctx.flags?.from === 'string' ? ctx.flags.from : '';
  let apps;
  try { apps = trackAApps(ctx.core).filter((a) => a.slug !== ctx.slug && draftComplete(a)); } catch { return null; }
  if (from) return apps.find((a) => a.slug === from)?.slug || null;
  const frame = ctx.app?.call?.fm?.frame;
  apps.sort((a, b) => Number(b.call.fm.frame === frame) - Number(a.call.fm.frame === frame) || mtime(join(b.dir, 'draft.md')) - mtime(join(a.dir, 'draft.md')));
  return apps[0]?.slug || null;
}

// ---------- scoped checks ----------
//
// Every A:* check (chain, mainnet, build-evidence, repo, build-window, submission) is about call.md,
// deployments.json, build-evidence.md or submission.md — never draft.md prose. An AI rewrite cannot
// fix them, so revise never sees them. And the check before `build` must not wait on evidence that
// only build / deploy / record / submission produce (at status in-review A:mainnet is an error until
// the deploy exists, which would deadlock build → deploy); check-submission and ready still enforce
// the full set.

const CORE_NOT_DRAFT = new Set(['status', 'deadline', 'frame', 'frontmatter', 'track', 'facts-file']);
const draftFixable = (e) => !CORE_NOT_DRAFT.has(e.name) && !/^A:/.test(e.name);
function laterStep(e, app) {
  if (e.name === 'A:build-evidence' || e.name === 'A:submission') return true;
  if (e.name === 'A:mainnet') return mainnetRequired(app) !== 'invalid';
  return false;
}

/** ctx whose core.runChecks only reports the errors `keep` accepts (warnings pass through). */
function withChecks(ctx, keep) {
  const core = Object.create(ctx.core);
  core.runChecks = async (...a) => {
    const r = await ctx.core.runChecks(...a);
    const results = r.results.filter((x) => x.level !== 'error' || keep(x, ctx));
    return { ...r, results, ok: !results.some((x) => x.level === 'error') };
  };
  return { ...ctx, core };
}

function scopedCheck(base, h, keep, doneText) {
  const errs = async (ctx) => (await h.checkErrors(ctx)).filter((e) => keep(e, ctx));
  return {
    ...base,
    async done(ctx) {
      const e = await errs(ctx);
      return e.length ? { done: false, reason: `${e.length} error(s): ${e.slice(0, 3).map((x) => x.name).join(', ')}` } : { done: true, reason: doneText };
    },
    async run(ctx) {
      const e = await errs(ctx);
      if (!e.length) return { ok: true, message: doneText };
      const people = e.filter((x) => !draftFixable(x));
      const hint = people.length ? ` — needs a person: ${people.map((x) => `${x.name} (${x.detail})`).join('; ')}` : ' — the revise step will fix them';
      return { ok: false, message: `${e.length} error(s): ${e.map((x) => x.name).join(', ')}${hint}` };
    },
    async verify(ctx) {
      const e = await errs(ctx);
      return e.length ? { level: 'error', detail: e.map((x) => `- ${x.name}: ${x.detail}`).join('\n') } : { level: 'ok', detail: doneText };
    },
  };
}

// ---------- the pipeline ----------

export default function pipeline(defaultSteps, h) {
  const by = Object.fromEntries(defaultSteps.map((s) => [s.id, s]));

  const source = {
    ...by.source,
    title: 'Paste the call text into source.md (skipped when the program profile already gave the criteria)',
    done(ctx) {
      const n = h.sourceText(ctx).length;
      if (n >= 120) return { done: true, reason: `source.md has ${n} chars of call text` };
      const c = realCriteria(ctx.app).length;
      if (c) return { done: true, reason: `${c} criteria already in call.md (program profile); source.md optional` };
      return { done: false, reason: n ? `source.md has only ${n} chars of call text (need 120+)` : 'source.md still holds only the template and call.md has no criteria' };
    },
  };

  const extract = {
    ...by.extract,
    needs: ['source'],
    done(ctx) {
      if (ctx.app?.call?.fm?.criteria === 'none') return { done: true, reason: 'criteria: none' };
      const n = realCriteria(ctx.app).length;
      return n ? { done: true, reason: `${n} criteria in call.md` } : { done: false, reason: 'call.md has no criteria table (or "criteria: none")' };
    },
  };

  const draft = {
    ...by.draft,
    title: 'Write the draft (copied from a sibling Track A draft when one exists, else AI)',
    needs: ['extract'],
    instructions: 'Copies the newest complete Track A sibling draft (no AI call); `fund run <slug> --from <slug2>` picks the sibling, `--no-copy` forces an AI draft.',
    async run(ctx) {
      const sib = pickSibling(ctx);
      if (!sib) return by.draft.run(ctx);
      const r = copyDraftFrom(sib, ctx.dir, ctx.app?.call?.fm?.program);
      return { ok: true, message: `copied draft.md from applications/${sib} (no AI call)${r.dropped.length ? `; dropped criterion ids not in this call: ${r.dropped.join(', ')}` : ''}` };
    },
  };

  const build = {
    id: 'build',
    title: 'forge build + test, write build-evidence.md (a:build)',
    kind: 'auto',
    estimate_h: 0,
    needs: ['check'],
    optional: false,
    done: (ctx) => evidenceState(ctx.app),
    async run(ctx) {
      const argv = ['a:build', '--slug', ctx.slug];
      const res = await call(ctx, argv);
      const head = res.lines.find((l) => /tests passing/.test(l));
      return outcome(res, argv, `build-evidence.md written${head ? `: ${head.replace(/^✓\s*/, '')}` : ''}`);
    },
    verify(ctx) {
      const s = evidenceState(ctx.app);
      if (!s.done) return { level: 'error', detail: s.reason };
      return { level: s.ev.tree && s.ev.tree !== 'clean' ? 'warn' : 'ok', detail: s.reason };
    },
  };

  const deploy = {
    id: 'deploy',
    title: 'Deploy ShelterSplit: a person signs and broadcasts',
    kind: 'human',
    estimate_h: 0.5,
    needs: ['build'],
    optional: false,
    // The action, not `fund done`: a:deploy prints the forge command to sign; a:record then marks
    // deploy and record done at once (both detect the deployments.json entry).
    command: (ctx) => deployState(ctx.app).deployCmd,
    instructions: 'Run fund a:deploy <chain> <network> for this app (chain: in applications/<slug>/call.md; mainnet when mainnet_required: true). `fund next <slug>` prints the exact command, `fund a:matrix` the deploy that unblocks most programs. a:deploy prints the env and the forge command; simulate with --simulate, then sign and broadcast it yourself with your keystore. Mainnet only after the tests, the AI security review and a human review. Then: fund done <slug> deploy',
    done(ctx) {
      const s = deployState(ctx.app);
      const p = deployProblem(s);
      if (p) return { done: false, reason: p };
      if (s.want.length) return { done: true, reason: `recorded: ${s.want.map((d) => `${d.chain} ${d.network} ${d.address.slice(0, 10)}…`).join(', ')}` };
      return { done: false, reason: `no ${s.chains.join('|')} ${s.network} deployment yet — run: ${s.deployCmd}, then sign and broadcast it yourself` };
    },
  };

  const record = {
    id: 'record',
    title: 'Record the real deployment (a:record)',
    kind: 'human',
    estimate_h: 0.1,
    needs: ['deploy'],
    optional: false,
    noOverride: true, // evidence is the deployments.json entry a:record writes
    command: (ctx) => { const s = deployState(ctx.app); return `fund a:record ${s.chain} ${s.network} <address> --tx <hash>`; },
    instructions: 'Copy the contract address and tx hash from the broadcast output, then: fund a:record <chain> <network> <address> --tx <hash>. Detected from tracks/a-build/deployments.json; `fund done` cannot stand in for it.',
    done(ctx) {
      const s = deployState(ctx.app);
      const p = deployProblem(s);
      if (p) return { done: false, reason: p };
      if (s.want.length) return { done: true, reason: `${s.want.length} ${s.network === 'mainnet' ? 'mainnet ' : ''}deployment(s) in deployments.json` };
      return { done: false, reason: `after broadcasting: fund a:record ${s.chain} ${s.network} <address> --tx <hash>` };
    },
  };

  const target = (ctx) => {
    const s = deployState(ctx.app);
    const d = s.want.find((x) => x.verified) || s.want[0] || null;
    if (!d) return { d: null };
    let env = '';
    try { env = networkInfo(loadChains(), d.chain, d.network).rpcEnv || ''; } catch { /* unknown chain: the A:chain check reports it */ }
    return { d, env };
  };

  const verifyDeploy = {
    id: 'verify-deploy',
    title: 'Read-only RPC check of the deployment (a:verify; skipped without an RPC env var)',
    kind: 'auto',
    estimate_h: 0,
    needs: ['record'],
    optional: true,
    done(ctx) {
      const { d, env } = target(ctx);
      if (!d) return { done: false, reason: 'no deployment recorded yet' };
      if (d.verified) return { done: true, reason: `${d.chain} ${d.network} ${d.address.slice(0, 10)}… verified on-chain${d.verifiedAt ? ` ${String(d.verifiedAt).slice(0, 10)}` : ''}` };
      if (!env || !process.env[env]) return { done: true, skipped: true, reason: `skipped (optional): set ${env || 'the RPC env var'} to verify ${d.chain} ${d.network} on-chain` };
      return { done: false, reason: `not verified yet — fund a:verify ${d.chain} ${d.network}` };
    },
    async run(ctx) {
      const { d } = target(ctx);
      if (!d) return { ok: false, message: 'no deployment recorded' };
      const argv = ['a:verify', d.chain, d.network];
      return outcome(await call(ctx, argv), argv, `verified ${d.chain} ${d.network} ${d.address.slice(0, 10)}… over RPC (read-only)`);
    },
    verify(ctx) {
      const { d } = target(ctx);
      if (!d) return { level: 'error', detail: 'no deployment recorded' };
      return d.verified ? { level: 'ok', detail: `${d.chain} ${d.network} verified` } : { level: 'warn', detail: `${d.chain} ${d.network} ${d.address} not verified on-chain — fund a:verify ${d.chain} ${d.network}` };
    },
  };

  const submission = {
    id: 'submission',
    title: 'Render submission.md from the profile, deployments and build evidence (a:submission)',
    kind: 'auto',
    estimate_h: 0,
    needs: ['build', 'record', 'verify-deploy'],
    optional: false,
    done: (ctx) => submissionState(ctx),
    async run(ctx) {
      const argv = ['a:submission', ctx.slug];
      return outcome(await call(ctx, argv), argv, 'wrote submission.md');
    },
    verify(ctx) { const s = submissionState(ctx); return { level: s.done ? 'ok' : 'error', detail: s.reason }; },
  };

  const check = {
    ...scopedCheck(by.check, h, (e, ctx) => !laterStep(e, ctx.app), 'fund check passes (deployment, build evidence and submission.md are checked by their own steps)'),
    title: 'Run fund check on the draft (the deployment, build evidence and submission have their own steps)',
  };

  const checkSubmission = {
    ...scopedCheck(by.check, h, () => true, 'fund check passes'),
    id: 'check-submission',
    title: 'fund check again with the deployment, evidence and submission in place',
    needs: ['submission'],
  };

  const review = { ...by.review, needs: ['check-submission'] };
  // The AI only ever sees (and is only triggered by) check errors it can fix in draft.md.
  const revise = {
    ...by.revise,
    needs: ['draft'],
    done: (ctx) => by.revise.done(withChecks(ctx, draftFixable)),
    run: (ctx) => by.revise.run(withChecks(ctx, draftFixable)),
  };

  const humanRead = {
    ...by['human-read'],
    needs: ['review', 'revise'],
    instructions: 'Read applications/<slug>/submission.md top to bottom next to call.md and the latest round in review.md. Open every explorer link, check the repo is public and the demo works. Fix draft.md if needed (fund run <slug> regenerates submission.md). When you would sign it: fund done <slug> human-read',
  };

  const ready = { ...by.ready, needs: ['human-read', 'check-submission'] };

  const submit = {
    ...by.submit,
    title: 'Paste submission.md into the program\'s form and submit',
    instructions: 'Open the program\'s form (url in call.md). Paste each section of applications/<slug>/submission.md into its field, add the repo and demo links, tick the checklist at the bottom, press submit yourself and keep the confirmation. Then: fund done <slug> submit',
  };

  return [source, extract, draft, check, build, deploy, record, verifyDeploy, submission, checkSubmission, review, revise, humanRead, ready, submit, by['record-submission']];
}
