import { readFileSync } from 'fs';
import { join } from 'path';
import { TOKEN_TAILS_HELD_WALLETS, autoChainIds, readShelterConfig } from './shelter-onchain.config';
import { CHAINS, WALLETS } from './wallet.config';

/*
 * wallet.config.ts is generated by `fund a:ingest` (and `fund a:backend-deployments`) from the same
 * records that write the client's public deployment lists. This spec keeps the two in sync: every split
 * the client lists is in the backend config and the other way round, with the same token symbol.
 */
const CLIENT = join(__dirname, '..', '..', '..', '..', 'client', 'public', 'shelter-payouts');
const list = (file: string): any[] => JSON.parse(readFileSync(join(CLIENT, file), 'utf8'));

describe('wallet.config.ts (generated) stays in sync with the client deployment lists', () => {
    for (const [network, file] of [
        ['mainnet', 'deployments.json'],
        ['testnet', 'testnet-deployments.json'],
    ] as const) {
        it(`${network}: the same ShelterSplit instances, tokens and deploy txs`, () => {
            const client = list(file)
                .map(
                    d =>
                        `${d.chainId}:${String(d.address).toLowerCase()}:${d.symbol || d.token || 'USDC'}:${d.tx || ''}`
                )
                .sort();
            const backend = Object.values(CHAINS)
                .filter(c => c.network === network)
                .flatMap(c => [...(c.split ? [c.split] : []), ...c.otherSplits].map(s => ({ c, s })))
                .map(({ c, s }) => `${c.chainId}:${s.address}:${s.token.symbol}:${s.deployTx || ''}`)
                .sort();
            expect(backend).toEqual(client);
        });
    }

    it('names one default split per chain, never a second token (EURC)', () => {
        for (const c of Object.values(CHAINS)) {
            if (!c.split) continue;
            expect(c.split.token.symbol).not.toBe('EURC');
            expect(c.token.symbol).toBe(c.split.token.symbol);
        }
    });

    it('carries Pink Paw, the testnet treasury and hot wallet, and the held wallet list agrees', () => {
        expect(WALLETS.mainnet.pinkPaw!.toLowerCase()).toBe(TOKEN_TAILS_HELD_WALLETS[0]);
        expect(WALLETS.testnet.treasury).toMatch(/^0x[0-9a-fA-F]{40}$/);
        expect(WALLETS.testnet.donateHot).toMatch(/^0x[0-9a-fA-F]{40}$/);
    });
});

describe('the recorded mainnet wave (2026-10-07) is what production serves', () => {
    // Specs of the pre-deploy rail mock wallet.config.ts without these (pre-mainnet.fakes-spec.ts).
    it('Arc mainnet defaults to the recorded USDC split and its DonateRouter', () => {
        const c = readShelterConfig({ SHELTER_NETWORK: 'mainnet' } as NodeJS.ProcessEnv);
        expect(c.chainId).toBe(5042);
        expect(c.splitAddress?.toLowerCase()).toBe('0x457c89e10a6e66633eda5bf82fd086febb5db147');
        expect(c.routerAddress?.toLowerCase()).toBe('0x937f13ce28294011567615330dbcb859a06a0bba');
        expect(c.autoChain).toBe(true);
    });

    it('serves the six other mainnets with a recorded split', () => {
        expect(autoChainIds(5042).sort((a, b) => a - b)).toEqual([143, 4217, 4663, 8453, 42161, 43114]);
    });
});
