// GENERATED by `fund a:ingest` (funding/framework/tracks/a-build/wave.mjs, walletConfig) from
// tracks/a-build/chains.json, deployments.json, router-deployments.json and wallets.public.json. Run
// `fund a:backend-deployments` to regenerate; do not edit by hand. wallet.config.spec.ts checks it
// against the client's public lists (client/public/shelter-payouts/deployments.json and
// testnet-deployments.json). Public addresses only: the hot wallet key stays in SHELTER_DONATE_PRIVATE_KEY.

export interface TokenInfo {
    symbol: string;
    decimals: number;
    /** Lowercased; null when not recorded. */
    address: string | null;
}

export interface SplitInstance {
    /** Lowercased ShelterSplit address. */
    address: string;
    /** The token this instance pays out. */
    token: TokenInfo;
    /** The deploy transaction: its receipt's block is where the impact indexer starts. */
    deployTx?: string;
    /** The deploy block, when recorded. */
    fromBlock?: number;
    /** The DonateRouter that pays into this split, when one is recorded. */
    router?: string;
    routerFromBlock?: number;
}

export interface ChainWallets {
    name: string;
    chainId: number;
    network: 'mainnet' | 'testnet';
    /** Keyless public RPC (an env override can name a paid one). */
    rpc: string;
    /** A keyless RPC for wide eth_getLogs ranges, when the default one caps them. */
    logRpc?: string;
    explorer: string;
    /** The chain's primary payout token. */
    token: TokenInfo;
    /** The split the backend defaults this chain to, or null before a deploy. */
    split: SplitInstance | null;
    /** Every other recorded instance (a second token such as EURC, an older deploy). */
    otherSplits: SplitInstance[];
}

export interface NetworkWallets {
    /** Pink Paw's payout wallet (held by Token Tails until the handover). */
    pinkPaw: string | null;
    /** The ShelterSplit treasury (remainder and rounding dust). */
    treasury: string | null;
    /** The address of SHELTER_DONATE_PRIVATE_KEY (treats, relay gas). */
    donateHot: string | null;
    /** The x402 demo agent. */
    agent: string | null;
    deployer: string | null;
}

export const WALLETS: Record<'mainnet' | 'testnet', NetworkWallets> = {
    mainnet: {
        pinkPaw: '0xE299299b846Ba629f5A591dBF4F562bcC07A0f37',
        treasury: '0x7b136b872bEad1dAE557d1286f125B7A8A197C9A',
        donateHot: '0x8D03d8295892F7dE2B7cE57585Aa45Dd4B3C2ba0',
        agent: '0x3333c1661B93f56DeC472eF89ACa03F56E70F9B7',
        deployer: '0xd6F37D1241dA20BbE40D1210940Bc43A1Ec56263',
    },
    testnet: {
        pinkPaw: '0xE299299b846Ba629f5A591dBF4F562bcC07A0f37',
        treasury: '0x7b136b872bEad1dAE557d1286f125B7A8A197C9A',
        donateHot: '0x8D03d8295892F7dE2B7cE57585Aa45Dd4B3C2ba0',
        agent: '0x3333c1661B93f56DeC472eF89ACa03F56E70F9B7',
        deployer: '0xd6F37D1241dA20BbE40D1210940Bc43A1Ec56263',
    },
};

export const CHAINS: Record<string, ChainWallets> = {
    arcMainnet: {
        name: 'Arc',
        chainId: 5042,
        network: 'mainnet',
        rpc: 'https://rpc.mainnet.arc.io',
        explorer: 'https://explorer.arc.io',
        token: {
            symbol: 'USDC',
            decimals: 6,
            address: '0x3600000000000000000000000000000000000000',
        },
        split: null,
        otherSplits: [],
    },
    arcTestnet: {
        name: 'Arc Testnet',
        chainId: 5042002,
        network: 'testnet',
        rpc: 'https://rpc.testnet.arc.io',
        logRpc: 'https://rpc.blockdaemon.testnet.arc.network',
        explorer: 'https://explorer.testnet.arc.io',
        token: {
            symbol: 'USDC',
            decimals: 6,
            address: '0x3600000000000000000000000000000000000000',
        },
        split: {
            address: '0x457c89e10a6e66633eda5bf82fd086febb5db147',
            token: {
                symbol: 'USDC',
                decimals: 6,
                address: '0x3600000000000000000000000000000000000000',
            },
            deployTx: '0x6af0fe0eae4abd65d8560cf4ed14ada55f2debd2e14e9306d45d81a271d0ede8',
            router: '0xa1cf1db2042dea0f169b1acdab479d4f17852860',
            routerFromBlock: 65428358,
        },
        otherSplits: [
            {
                address: '0x937f13ce28294011567615330dbcb859a06a0bba',
                token: {
                    symbol: 'EURC',
                    decimals: 6,
                    address: '0x89b50855aa3be2f677cd6303cec089b5f319d72a',
                },
                deployTx: '0xc63d3c5786aaf15474c0d74c5c65f6e0dcd33d232bdbbee0141a83313a1e59a3',
                router: '0x47ed389d2af5f4cd3e884208b72d609e78f6c5df',
                routerFromBlock: 65428367,
            },
        ],
    },
    baseMainnet: {
        name: 'Base',
        chainId: 8453,
        network: 'mainnet',
        rpc: 'https://mainnet.base.org',
        explorer: 'https://basescan.org',
        token: {
            symbol: 'USDC',
            decimals: 6,
            address: '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913',
        },
        split: null,
        otherSplits: [],
    },
    baseTestnet: {
        name: 'Base Sepolia',
        chainId: 84532,
        network: 'testnet',
        rpc: 'https://sepolia.base.org',
        logRpc: 'https://base-sepolia-rpc.publicnode.com',
        explorer: 'https://sepolia.basescan.org',
        token: {
            symbol: 'USDC',
            decimals: 6,
            address: '0x036cbd53842c5426634e7929541ec2318f3dcf7e',
        },
        split: {
            address: '0x8bf026d3816cb2344d14aa6301fccde3b289878c',
            token: {
                symbol: 'USDC',
                decimals: 6,
                address: '0x036cbd53842c5426634e7929541ec2318f3dcf7e',
            },
            deployTx: '0x11bb6a6c264480a7fba025b2b94c7d4b7693e377d5f3289ab8dbe79de0d0b790',
            router: '0x683d66d89eaa7460d3a12337cdf8185fae37dfbd',
            routerFromBlock: 47667479,
        },
        otherSplits: [
            {
                address: '0x457c89e10a6e66633eda5bf82fd086febb5db147',
                token: {
                    symbol: 'USDC',
                    decimals: 6,
                    address: '0x036cbd53842c5426634e7929541ec2318f3dcf7e',
                },
                deployTx: '0x362b82466a4ba86c267bc3f05aea2c4e688d31f53271293050eab1106d293fc6',
            },
        ],
    },
    arbitrumMainnet: {
        name: 'Arbitrum One',
        chainId: 42161,
        network: 'mainnet',
        rpc: 'https://arb1.arbitrum.io/rpc',
        explorer: 'https://arbiscan.io',
        token: {
            symbol: 'USDC',
            decimals: 6,
            address: '0xaf88d065e77c8cc2239327c5edb3a432268e5831',
        },
        split: null,
        otherSplits: [],
    },
    arbitrumTestnet: {
        name: 'Arbitrum Sepolia',
        chainId: 421614,
        network: 'testnet',
        rpc: 'https://sepolia-rollup.arbitrum.io/rpc',
        explorer: 'https://sepolia.arbiscan.io',
        token: {
            symbol: 'USDC',
            decimals: 6,
            address: '0x75faf114eafb1bdbe2f0316df893fd58ce46aa4d',
        },
        split: {
            address: '0x457c89e10a6e66633eda5bf82fd086febb5db147',
            token: {
                symbol: 'USDC',
                decimals: 6,
                address: '0x75faf114eafb1bdbe2f0316df893fd58ce46aa4d',
            },
            deployTx: '0x3f51b51be745eac9ff65434ca4fc8e1ef15dd815c8bdce89decd74439f8f8845',
            router: '0xe271131be71e29f83084fd34aa6c70d50a2aea71',
            routerFromBlock: 315618031,
        },
        otherSplits: [],
    },
    robinhoodMainnet: {
        name: 'Robinhood Chain',
        chainId: 4663,
        network: 'mainnet',
        rpc: 'https://rpc.mainnet.chain.robinhood.com',
        explorer: 'https://robinhoodchain.blockscout.com',
        token: {
            symbol: 'USDG',
            decimals: 6,
            address: '0x5fc5360d0400a0fd4f2af552add042d716f1d168',
        },
        split: null,
        otherSplits: [],
    },
    robinhoodTestnet: {
        name: 'Robinhood Chain Testnet',
        chainId: 46630,
        network: 'testnet',
        rpc: 'https://rpc.testnet.chain.robinhood.com',
        explorer: 'https://explorer.testnet.chain.robinhood.com',
        token: {
            symbol: 'mUSDC',
            decimals: 6,
            address: '0x457c89e10a6e66633eda5bf82fd086febb5db147',
        },
        split: {
            address: '0x2d42d01a00d75ade8c4f9503a7a6cee8a5f34777',
            token: {
                symbol: 'mUSDC',
                decimals: 6,
                address: '0x457c89e10a6e66633eda5bf82fd086febb5db147',
            },
            deployTx: '0xf36898d4824c4906bdde2c36792a01c84c12725441cbeb50167cc009931d6881',
        },
        otherSplits: [],
    },
    avalancheMainnet: {
        name: 'Avalanche C-Chain',
        chainId: 43114,
        network: 'mainnet',
        rpc: 'https://api.avax.network/ext/bc/C/rpc',
        explorer: 'https://subnets.avax.network/c-chain',
        token: {
            symbol: 'USDC',
            decimals: 6,
            address: '0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e',
        },
        split: null,
        otherSplits: [],
    },
    avalancheTestnet: {
        name: 'Avalanche Fuji',
        chainId: 43113,
        network: 'testnet',
        rpc: 'https://api.avax-test.network/ext/bc/C/rpc',
        explorer: 'https://subnets-test.avax.network/c-chain',
        token: {
            symbol: 'USDC',
            decimals: 6,
            address: '0x5425890298aed601595a70ab815c96711a31bc65',
        },
        split: {
            address: '0x8bf026d3816cb2344d14aa6301fccde3b289878c',
            token: {
                symbol: 'USDC',
                decimals: 6,
                address: '0x5425890298aed601595a70ab815c96711a31bc65',
            },
            deployTx: '0xe9cc74604e31824540f51d45bb47ad43ea41011cecf51542f855230ef6edfcc8',
            router: '0x4b25318bf32f2740c086350f802452ef2095cb6f',
            routerFromBlock: 59029760,
        },
        otherSplits: [
            {
                address: '0x457c89e10a6e66633eda5bf82fd086febb5db147',
                token: {
                    symbol: 'USDC',
                    decimals: 6,
                    address: '0x5425890298aed601595a70ab815c96711a31bc65',
                },
                deployTx: '0xec70639ad5a7065eefd03e8006b5f41f6f68c3dcb4cd15784e63c156db8db904',
            },
            {
                address: '0x6f0a33ec63cb79dcc13eff6f31795cd11b38a022',
                token: {
                    symbol: 'EURC',
                    decimals: 6,
                    address: '0x5e44db7996c682e92a960b65ac713a54ad815c6b',
                },
                deployTx: '0x8885ce01c16b6bebae57e9066078adf169a55df9fe5c0a3eca35721659c6f0f3',
                router: '0xa1cf1db2042dea0f169b1acdab479d4f17852860',
                routerFromBlock: 59029763,
            },
        ],
    },
    tempoMainnet: {
        name: 'Tempo',
        chainId: 4217,
        network: 'mainnet',
        rpc: 'https://rpc.tempo.xyz',
        explorer: 'https://explore.tempo.xyz',
        token: {
            symbol: 'USDC.e',
            decimals: 6,
            address: '0x20c000000000000000000000b9537d11c60e8b50',
        },
        split: null,
        otherSplits: [],
    },
    tempoTestnet: {
        name: 'Tempo Moderato',
        chainId: 42431,
        network: 'testnet',
        rpc: 'https://rpc.moderato.tempo.xyz',
        explorer: 'https://explore.testnet.tempo.xyz',
        token: {
            symbol: 'pathUSD',
            decimals: 6,
            address: '0x20c0000000000000000000000000000000000000',
        },
        split: {
            address: '0x9978e60da2352a8de02852788d34bd95849a598d',
            token: {
                symbol: 'pathUSD',
                decimals: 6,
                address: '0x20c0000000000000000000000000000000000000',
            },
            deployTx: '0x8169cd8ca20c3e9a793185c5ef686ed38a460a799abddd075adc74672a0e2575',
        },
        otherSplits: [],
    },
    monadMainnet: {
        name: 'Monad',
        chainId: 143,
        network: 'mainnet',
        rpc: 'https://rpc.monad.xyz',
        logRpc: 'https://rpc1.monad.xyz',
        explorer: 'https://monadvision.com',
        token: {
            symbol: 'USDC',
            decimals: 6,
            address: '0x754704bc059f8c67012fed69bc8a327a5aafb603',
        },
        split: null,
        otherSplits: [],
    },
    monadTestnet: {
        name: 'Monad Testnet',
        chainId: 10143,
        network: 'testnet',
        rpc: 'https://testnet-rpc.monad.xyz',
        logRpc: 'https://monad-testnet.api.onfinality.io/public',
        explorer: 'https://testnet.monadvision.com',
        token: {
            symbol: 'USDC',
            decimals: 6,
            address: '0x534b2f3a21130d7a60830c2df862319e593943a3',
        },
        split: {
            address: '0x457c89e10a6e66633eda5bf82fd086febb5db147',
            token: {
                symbol: 'USDC',
                decimals: 6,
                address: '0x534b2f3a21130d7a60830c2df862319e593943a3',
            },
            deployTx: '0x91108a6f79c8da351b5caa39875b497808b4a423580891d480d25cf27b0c0489',
            router: '0xe271131be71e29f83084fd34aa6c70d50a2aea71',
            routerFromBlock: 68136782,
        },
        otherSplits: [],
    },
};
