/**
 * GENERATED by client/scripts/sync-fonts.mjs from the pinned Fontsource packages. Do not edit.
 * Run `npm run fonts:sync` in client/ after changing the font packages or the script.
 */

/** Latin files `_document` preloads, with the same `?v=` URLs as the `@font-face` rules. */
export const PRELOAD_FONT_FILES: ReadonlyArray<string> = ["/fonts/passion-one-latin-400-normal.woff2?v=eb49ce211d","/fonts/bebas-neue-latin-400-normal.woff2?v=a7c90c8924"];
