// GENERATED by catnip-heist `npm run build:client` (vite.config.ts). Do not edit.
// The Cat Yard HOME module (shared/home-yard.ts), served from client/public/heist-game.
export const HOME_YARD_ENTRY = "/heist-game/build/home-CvqBlbhK.js";
