/**
 * GENERATED by client/scripts/sync-fonts.mjs from the pinned Fontsource packages. Do not edit.
 * Run `npm run fonts:sync` in client/ after changing the font packages or the script.
 *
 * Catnip Heist copy of the brand body face (decision #85: secondary text in Nunito instead of
 * system-ui). The woff2 files live in catnip-heist/public/fonts/.
 */

/** Font files shipped in public/fonts/ (relative to that directory). */
export const HEIST_FONT_FILES: ReadonlyArray<string> = ["nunito-latin-wght-normal.woff2","nunito-latin-ext-wght-normal.woff2"];

/** The stack for Heist secondary text: Nunito, then its metric-matched fallback. */
export const HEIST_BODY_FONT = "'Nunito', 'Nunito Fallback', 'Nunito Fallback Android', ui-rounded, system-ui, sans-serif";

/**
 * The `@font-face` rules, with URLs under `fontsBase` (a directory URL ending in `/`, for example
 * `fonts/` for the relative dev and CDN builds, or `${DEPLOY_BASE}fonts/`).
 */
export function heistFontFaceCss(fontsBase: string): string {
  return `@font-face {
  font-family: "Nunito";
  font-style: normal;
  font-weight: 200 1000;
  font-display: swap;
  src: url("${fontsBase}nunito-latin-wght-normal.woff2?v=ba344451ea") format("woff2-variations"), url("${fontsBase}nunito-latin-wght-normal.woff2?v=ba344451ea") format("woff2");
  unicode-range: U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;
}
@font-face {
  font-family: "Nunito";
  font-style: normal;
  font-weight: 200 1000;
  font-display: swap;
  src: url("${fontsBase}nunito-latin-ext-wght-normal.woff2?v=2c8d792869") format("woff2-variations"), url("${fontsBase}nunito-latin-ext-wght-normal.woff2?v=2c8d792869") format("woff2");
  unicode-range: U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF;
}
/* nunito on arial */
@font-face {
  font-family: "Nunito Fallback";
  font-style: normal;
  font-weight: 200 599;
  src: local("Arial"), local("ArialMT"), local("Liberation Sans"), local("Roboto");
  size-adjust: 101.39%;
  ascent-override: 99.71%;
  descent-override: 34.82%;
  line-gap-override: 0.00%;
}
/* nunito/700 on arial/700 */
@font-face {
  font-family: "Nunito Fallback";
  font-style: normal;
  font-weight: 600 749;
  src: local("Arial Bold"), local("Arial-BoldMT"), local("Liberation Sans Bold");
  size-adjust: 97.92%;
  ascent-override: 103.25%;
  descent-override: 36.05%;
  line-gap-override: 0.00%;
}
/* nunito/700 on roboto/700 */
@font-face {
  font-family: "Nunito Fallback Android";
  font-style: normal;
  font-weight: 600 749;
  src: local("Roboto Bold");
  size-adjust: 103.95%;
  ascent-override: 97.26%;
  descent-override: 33.96%;
  line-gap-override: 0.00%;
}
/* nunito/800 on arial/700 */
@font-face {
  font-family: "Nunito Fallback";
  font-style: normal;
  font-weight: 750 1000;
  src: local("Arial Bold"), local("Arial-BoldMT"), local("Liberation Sans Bold");
  size-adjust: 100.21%;
  ascent-override: 100.89%;
  descent-override: 35.23%;
  line-gap-override: 0.00%;
}
/* nunito/800 on roboto/700 */
@font-face {
  font-family: "Nunito Fallback Android";
  font-style: normal;
  font-weight: 750 1000;
  src: local("Roboto Bold");
  size-adjust: 106.38%;
  ascent-override: 95.04%;
  descent-override: 33.18%;
  line-gap-override: 0.00%;
}`;
}
