// GENERATED by scripts/sync-contracts.mjs from shared/errors.ts. Do not edit this copy:
// edit shared/errors.ts, then run `node scripts/sync-contracts.mjs`.
/**
 * Error codes returned in API error bodies as `{ code, message }` (plan F5.6). One uppercase
 * vocabulary for every package; the lowercase `email-unverified` and `account-conflict` from the
 * early G9 draft are not used.
 *
 * Framework-free and TypeScript 4.8 compatible. Edit here, then run `node scripts/sync-contracts.mjs`.
 */
export const ErrorCode = {
    GUEST_FORBIDDEN: 'GUEST_FORBIDDEN',
    GUEST_SESSION_REQUIRED: 'GUEST_SESSION_REQUIRED',
    ACCOUNT_CONFLICT: 'ACCOUNT_CONFLICT',
    EMAIL_UNVERIFIED: 'EMAIL_UNVERIFIED',
    STARTER_LOCKED: 'STARTER_LOCKED',
    NAME_TOO_SHORT: 'NAME_TOO_SHORT',
    NAME_TOO_LONG: 'NAME_TOO_LONG',
    NAME_CHARS: 'NAME_CHARS',
    NAME_RESERVED: 'NAME_RESERVED',
    NAME_BLOCKED: 'NAME_BLOCKED',
    HEIST_REPLAY_INVALID: 'HEIST_REPLAY_INVALID',
    HEIST_NOT_WON: 'HEIST_NOT_WON',
    HEIST_TRAILING_INPUT: 'HEIST_TRAILING_INPUT',
    HEIST_SIM_VERSION: 'HEIST_SIM_VERSION',
    HEIST_DUPLICATE: 'HEIST_DUPLICATE',
    DONATE_PAUSED: 'DONATE_PAUSED',
    DONATE_BUDGET_SPENT: 'DONATE_BUDGET_SPENT',
    DONATE_SEND_FAILED: 'DONATE_SEND_FAILED',
    DONATE_ALREADY_TODAY: 'DONATE_ALREADY_TODAY',
    DONATE_NOT_ELIGIBLE: 'DONATE_NOT_ELIGIBLE',
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];

export const ERROR_CODES: ErrorCode[] = Object.keys(ErrorCode).map(key => ErrorCode[key as keyof typeof ErrorCode]);

/** True when `value` is a known error code. */
export function isErrorCode(value: unknown): value is ErrorCode {
    return typeof value === 'string' && ERROR_CODES.indexOf(value as ErrorCode) !== -1;
}

/**
 * Reads the error code from a parsed error body (`{ code }`, or Nest's `{ message: { code } }` when
 * an exception was thrown with an object). Returns null for anything else. Never throws.
 */
export function errorCodeOf(body: unknown): ErrorCode | null {
    if (!body || typeof body !== 'object') {
        return null;
    }
    const record = body as { code?: unknown; message?: unknown };
    if (isErrorCode(record.code)) {
        return record.code;
    }
    const nested = record.message;
    if (nested && typeof nested === 'object' && isErrorCode((nested as { code?: unknown }).code)) {
        return (nested as { code: ErrorCode }).code;
    }
    return null;
}
