// GENERATED by scripts/sync-contracts.mjs from shared/__tests__/caps.test.ts. Do not edit this copy:
// edit shared/__tests__/caps.test.ts, then run `node scripts/sync-contracts.mjs`.
import {
    CATNIP_CHAOS_ENDLESS_CAP,
    CATNIP_CHAOS_LEVEL_CAPS,
    CATNIP_CHAOS_LEVELS,
    CATNIP_CHAOS_TOTAL_CAP,
    GUEST_TAILS_LIFETIME_CAP,
    HEIST_LEVEL_CAPS,
    HEIST_MAX_ID_LENGTH,
    HEIST_MAX_RUNS,
    HEIST_MAX_TICKS,
    MATCH3_LEVEL_CATNIP_CAPS,
    MATCH3_LEVELS,
    MATCH3_TOTAL_CAP,
    PLEDGE_DAILY_CAP,
    REWARDS,
    SEASON_EVENT_LEVEL_POINT_CAPS,
    SEASON_EVENT_LEVELS,
    TOTAL_CATNIP_CAP,
} from '../caps';

describe('shared caps', () => {
    it('raises the endless and Cupid Cat caps from 420 to 500 (decision #57)', () => {
        expect(CATNIP_CHAOS_ENDLESS_CAP).toBe(500);
        expect(CATNIP_CHAOS_LEVEL_CAPS[0]).toBe(500);
        expect(SEASON_EVENT_LEVEL_POINT_CAPS.every(cap => cap === 500)).toBe(true);
        expect(SEASON_EVENT_LEVELS).toHaveLength(14);
    });

    it('lists the 97 Purrsuit levels in save order', () => {
        expect(CATNIP_CHAOS_LEVELS).toHaveLength(97);
        expect(CATNIP_CHAOS_LEVELS.slice(0, 3)).toEqual(['01', '11', '12']);
        expect(CATNIP_CHAOS_LEVELS[CATNIP_CHAOS_LEVELS.length - 1]).toBe('166');
        expect(CATNIP_CHAOS_LEVEL_CAPS.slice(1).every(cap => cap === 10)).toBe(true);
    });

    it('keeps the Paw Match cap curve', () => {
        expect(MATCH3_LEVEL_CATNIP_CAPS).toHaveLength(30);
        expect(MATCH3_LEVEL_CATNIP_CAPS[0]).toBe(11);
        expect(MATCH3_LEVEL_CATNIP_CAPS[29]).toBe(76);
    });

    it('derives the totals, 80 higher than with the 420 cap', () => {
        expect(CATNIP_CHAOS_TOTAL_CAP).toBe(500 + 96 * 10);
        expect(TOTAL_CATNIP_CAP).toBe(CATNIP_CHAOS_TOTAL_CAP + MATCH3_TOTAL_CAP);
        expect(TOTAL_CATNIP_CAP - 80).toBe(420 + 96 * 10 + MATCH3_TOTAL_CAP);
    });

    it('pins the guest, pledge and Heist limits', () => {
        expect(GUEST_TAILS_LIFETIME_CAP).toBe(2000);
        expect(PLEDGE_DAILY_CAP).toBe(5000);
        expect(HEIST_LEVEL_CAPS).toEqual([250, 240, 220, 270, 240, 240, 240, 310]);
    });

    it('bounds Heist run logs to the replay default of 10 minutes at 30 Hz', () => {
        expect(HEIST_MAX_TICKS).toBe(18000);
        expect(HEIST_MAX_RUNS).toBeLessThanOrEqual(HEIST_MAX_TICKS);
        expect(HEIST_MAX_ID_LENGTH).toBe(64);
    });

    it('freezes every shared table so no consumer can change the enforced caps', () => {
        [
            CATNIP_CHAOS_LEVELS,
            CATNIP_CHAOS_LEVEL_CAPS,
            MATCH3_LEVELS,
            MATCH3_LEVEL_CATNIP_CAPS,
            SEASON_EVENT_LEVELS,
            SEASON_EVENT_LEVEL_POINT_CAPS,
            HEIST_LEVEL_CAPS,
            REWARDS,
        ].forEach(table => expect(Object.isFrozen(table)).toBe(true));
        expect(() => (CATNIP_CHAOS_LEVEL_CAPS as number[]).push(1)).toThrow();
        expect(() => {
            (CATNIP_CHAOS_LEVEL_CAPS as number[])[0] = 9999;
        }).toThrow();
        expect(CATNIP_CHAOS_LEVEL_CAPS[0]).toBe(500);
    });
});
