// GENERATED by scripts/sync-contracts.mjs from shared/__tests__/enums.test.ts. Do not edit this copy:
// edit shared/__tests__/enums.test.ts, then run `node scripts/sync-contracts.mjs`.
import {
    BLESSING_STATUSES,
    CAT_ABILITY_TYPES,
    CAT_ORIGINS,
    DONATE_SOURCES,
    GameType,
    HANDOVER_STATUSES,
    isOneOf,
    LIVE_GAME_OUTCOMES,
    OrderStatus,
    PARTNER_STATUSES,
    RescueGoalStatus,
    SHELTER_ROLES,
    ShelterDonationStatus,
    STARTER_BREEDS,
} from '../enums';

describe('shared enums', () => {
    it('keeps every GameType value stored in old rows and adds CATNIP_HEIST', () => {
        expect(Object.values(GameType)).toEqual([
            'SHELTER',
            'HOME',
            'PURRQUEST',
            'CATBASSADORS',
            'CATNIP_CHAOS',
            'PIXEL_RESCUE',
            'MATCH_3',
            'CATNIP_HEIST',
        ]);
    });

    it('matches the client stop outcomes plus timeout', () => {
        expect(LIVE_GAME_OUTCOMES).toEqual(['won', 'died', 'timeout', 'quit']);
    });

    it('lists the five starters of decision #19 in order', () => {
        expect(STARTER_BREEDS).toEqual(['SCOUT', 'PINKIE', 'SHADOW', 'MISTY', 'SUNNY']);
    });

    it('extends OrderStatus and ShelterDonationStatus without renaming stored values', () => {
        expect(Object.values(OrderStatus)).toEqual(['COMPLETE', 'PENDING', 'LOCKED', 'FAILED', 'FAILED_GRANT']);
        expect(Object.values(ShelterDonationStatus)).toEqual(['PENDING', 'SENT', 'CONFIRMED', 'FAILED']);
        expect(Object.values(RescueGoalStatus)).toEqual(['OPEN', 'FILLED', 'DELIVERED', 'CANCELLED']);
    });

    it('keeps the lowercase vocabularies', () => {
        expect(DONATE_SOURCES).toEqual(['heist', 'page']);
        expect(CAT_ORIGINS).toEqual(['starter', 'pack', 'redeem', 'adopt', 'portrait']);
        expect(SHELTER_ROLES).toEqual(['partner', 'house']);
        expect(PARTNER_STATUSES).toEqual(['active', 'past', 'prospect']);
        expect(HANDOVER_STATUSES).toEqual(['held-by-token-tails', 'handed-over']);
    });

    it('lists every value of the list-backed enums', () => {
        expect(CAT_ABILITY_TYPES).toHaveLength(10);
        expect(BLESSING_STATUSES).toEqual(['WAITING', 'RECOVERING', 'ADOPTED', 'HEAVEN']);
    });

    it('freezes every shared list so no importer can mutate it for the whole process', () => {
        [
            LIVE_GAME_OUTCOMES,
            STARTER_BREEDS,
            CAT_ORIGINS,
            DONATE_SOURCES,
            SHELTER_ROLES,
            PARTNER_STATUSES,
            HANDOVER_STATUSES,
            CAT_ABILITY_TYPES,
            BLESSING_STATUSES,
        ].forEach(list => expect(Object.isFrozen(list)).toBe(true));
        expect(() => (STARTER_BREEDS as string[]).push('TABBY')).toThrow();
    });

    it('narrows unknown input with isOneOf', () => {
        expect(isOneOf(DONATE_SOURCES, 'heist')).toBe(true);
        expect(isOneOf(DONATE_SOURCES, 'game')).toBe(false);
        expect(isOneOf(DONATE_SOURCES, 1)).toBe(false);
        expect(isOneOf(DONATE_SOURCES, undefined)).toBe(false);
    });
});
