// GENERATED by scripts/sync-contracts.mjs from shared/__tests__/heist-bridge.test.ts. Do not edit this copy:
// edit shared/__tests__/heist-bridge.test.ts, then run `node scripts/sync-contracts.mjs`.
import {
    HEIST_BRIDGE_CHANNEL,
    HEIST_BRIDGE_VERSION,
    heistMessage,
    HeistRunCompleteMessage,
    HeistSessionMessage,
    isHeistRunLog,
    isHeistToHostMessage,
    isHostToHeistMessage,
} from '../heist-bridge';
import { HEIST_MAX_ID_LENGTH, HEIST_MAX_RUNS, HEIST_MAX_TICKS } from '../caps';

const log = {
    levelId: 'heist-01',
    simVersion: 1,
    seed: 1,
    catIds: ['scout', 'pinkie'] as [string, string],
    ticks: 120,
    runs: [
        [1, 0, 0, 60],
        [0, 1, 2, 60],
    ] as [number, number, number, number][],
};

describe('heist bridge', () => {
    it('stamps channel and version', () => {
        expect(heistMessage({ type: 'hello' })).toEqual({
            type: 'hello',
            channel: HEIST_BRIDGE_CHANNEL,
            v: HEIST_BRIDGE_VERSION,
        });
    });

    it('accepts every well-formed host message', () => {
        const session = heistMessage<HeistSessionMessage>({
            type: 'session',
            signedIn: true,
            progress: { levels: { 'heist-01': { won: true, bestScore: 200, stars: 3 } } },
            insets: { top: 44, right: 0, bottom: 34, left: 0 },
        });
        expect(isHostToHeistMessage(session)).toBe(true);
        expect(isHostToHeistMessage({ ...session, progress: null })).toBe(true);
        expect(isHostToHeistMessage(heistMessage({ type: 'save-result', runId: 'r1', status: 'saved' }))).toBe(true);
        expect(
            isHostToHeistMessage(
                heistMessage({ type: 'save-result', runId: 'r1', status: 'rejected', code: 'HEIST_REPLAY_INVALID' })
            )
        ).toBe(true);
        ['hello', 'pause', 'resume'].forEach(type =>
            expect(isHostToHeistMessage(heistMessage({ type } as never))).toBe(true)
        );        expect(
            isHostToHeistMessage(heistMessage({ type: 'audio', muted: true, musicVolume: 0.4, effectsVolume: 0 }))
        ).toBe(true);
    });

    it('rejects audio settings out of range or of the wrong type', () => {
        const audio = (extra: Record<string, unknown>) =>
            heistMessage({ type: 'audio', muted: false, musicVolume: 0.4, effectsVolume: 0.6, ...extra } as never);
        expect(isHostToHeistMessage(audio({}))).toBe(true);
        expect(isHostToHeistMessage(audio({ muted: 'no' }))).toBe(false);
        expect(isHostToHeistMessage(audio({ musicVolume: 1.5 }))).toBe(false);
        expect(isHostToHeistMessage(audio({ effectsVolume: -0.1 }))).toBe(false);
        expect(isHostToHeistMessage(audio({ musicVolume: NaN }))).toBe(false);
        expect(isHostToHeistMessage(audio({ effectsVolume: undefined }))).toBe(false);
    });

    it('rejects malformed host messages and heist messages sent the wrong way', () => {
        expect(
            isHostToHeistMessage(
                heistMessage({
                    type: 'session',
                    signedIn: 'yes',
                    progress: null,
                    insets: { top: 0, right: 0, bottom: 0, left: 0 },
                } as never)
            )
        ).toBe(false);
        expect(
            isHostToHeistMessage(
                heistMessage({
                    type: 'session',
                    signedIn: true,
                    progress: null,
                    insets: { top: NaN, right: 0, bottom: 0, left: 0 },
                } as never)
            )
        ).toBe(false);
        expect(isHostToHeistMessage(heistMessage({ type: 'save-result', runId: 'r1', status: 'maybe' } as never))).toBe(
            false
        );
        expect(isHostToHeistMessage(heistMessage({ type: 'ready' }))).toBe(false);
        expect(isHostToHeistMessage({ type: 'hello' })).toBe(false);
        expect(isHostToHeistMessage({ type: 'hello', channel: HEIST_BRIDGE_CHANNEL, v: 2 })).toBe(false);
        [null, undefined, 'hello', 1, []].forEach(value => expect(isHostToHeistMessage(value)).toBe(false));
    });

    it('accepts well-formed heist messages', () => {
        const done = heistMessage<HeistRunCompleteMessage>({
            type: 'run-complete',
            runId: 'r1',
            won: true,
            levelId: 'heist-01',
            log,
        });
        expect(isHeistToHostMessage(done)).toBe(true);
        ['ready', 'request-sign-in', 'exit'].forEach(type =>
            expect(isHeistToHostMessage(heistMessage({ type } as never))).toBe(true)
        );
    });

    it('rejects run-complete with a bad log, empty run id or mismatched level', () => {
        const base = { type: 'run-complete', runId: 'r1', won: true, levelId: 'heist-01', log };
        expect(isHeistToHostMessage(heistMessage({ ...base, runId: '' } as never))).toBe(false);
        expect(isHeistToHostMessage(heistMessage({ ...base, levelId: 'heist-02' } as never))).toBe(false);
        expect(isHeistToHostMessage(heistMessage({ ...base, log: { ...log, runs: [[1, 0, 0]] } } as never))).toBe(
            false
        );
        expect(isHeistToHostMessage(heistMessage({ ...base, log: { ...log, catIds: ['one'] } } as never))).toBe(false);
        expect(isHeistToHostMessage(heistMessage({ type: 'hello' }))).toBe(false);
    });

    it('checks run log structure', () => {
        expect(isHeistRunLog(log)).toBe(true);
        expect(isHeistRunLog({ ...log, ticks: '120' })).toBe(false);
        expect(isHeistRunLog(null)).toBe(false);
    });

    describe('run log bounds', () => {
        const run = (count: number) => [0, 0, 0, count] as [number, number, number, number];
        const long = 'x'.repeat(HEIST_MAX_ID_LENGTH + 1);

        it('accepts a log at the tick limit', () => {
            expect(isHeistRunLog({ ...log, ticks: HEIST_MAX_TICKS, runs: [run(HEIST_MAX_TICKS)] })).toBe(true);
            expect(isHeistRunLog({ ...log, ticks: 0, runs: [] })).toBe(true);
        });

        it('rejects more ticks than the limit', () => {
            expect(isHeistRunLog({ ...log, ticks: HEIST_MAX_TICKS + 1, runs: [run(HEIST_MAX_TICKS + 1)] })).toBe(false);
            expect(isHeistRunLog({ ...log, ticks: 1e12, runs: [run(1e12)] })).toBe(false);
        });

        it('rejects more runs than the limit before walking them', () => {
            const runs = Array.from({ length: HEIST_MAX_RUNS + 1 }, () => run(1));
            expect(isHeistRunLog({ ...log, ticks: runs.length, runs })).toBe(false);
        });

        it('requires the run counts to add up to ticks', () => {
            expect(isHeistRunLog({ ...log, ticks: 121 })).toBe(false);
            expect(isHeistRunLog({ ...log, ticks: 119 })).toBe(false);
        });

        it('requires non-negative integers', () => {
            expect(isHeistRunLog({ ...log, ticks: 120.5 })).toBe(false);
            expect(isHeistRunLog({ ...log, seed: -1 })).toBe(false);
            expect(isHeistRunLog({ ...log, seed: 1.5 })).toBe(false);
            expect(isHeistRunLog({ ...log, seed: 2 ** 32 })).toBe(false);
            expect(isHeistRunLog({ ...log, simVersion: -1 })).toBe(false);
            expect(isHeistRunLog({ ...log, simVersion: 1.5 })).toBe(false);
        });

        it('rejects bad run fields', () => {
            const bad = (r: unknown[]) => isHeistRunLog({ ...log, ticks: 1, runs: [r] });
            expect(bad([0, 0, 0, 1])).toBe(true);
            expect(bad([-1, 1, 7, 1])).toBe(true);
            expect(bad([0, 0, 0, 0])).toBe(false);
            expect(bad([0, 0, 0, -1])).toBe(false);
            expect(bad([0, 0, 0, 0.5])).toBe(false);
            expect(bad([2, 0, 0, 1])).toBe(false);
            expect(bad([0, 0.5, 0, 1])).toBe(false);
            expect(bad([0, 0, 8, 1])).toBe(false);
            expect(bad([0, 0, -1, 1])).toBe(false);
            expect(bad([0, 0, 1.5, 1])).toBe(false);
        });

        it('caps id lengths', () => {
            expect(isHeistRunLog({ ...log, levelId: long })).toBe(false);
            expect(isHeistRunLog({ ...log, levelId: '' })).toBe(false);
            expect(isHeistRunLog({ ...log, catIds: ['scout', long] })).toBe(false);
            expect(isHeistRunLog({ ...log, catIds: ['scout', ''] })).toBe(false);
            const base = { type: 'run-complete', runId: 'r1', won: true, levelId: 'heist-01', log };
            expect(isHeistToHostMessage(heistMessage({ ...base, runId: long } as never))).toBe(false);
            expect(
                isHostToHeistMessage(heistMessage({ type: 'save-result', runId: long, status: 'saved' } as never))
            ).toBe(false);
            expect(
                isHostToHeistMessage(heistMessage({ type: 'save-result', runId: '', status: 'saved' } as never))
            ).toBe(false);
        });
    });
});
