// GENERATED by scripts/sync-contracts.mjs from shared/__tests__/storefront.test.ts. Do not edit this copy:
// edit shared/__tests__/storefront.test.ts, then run `node scripts/sync-contracts.mjs`.
import {
    emptyStorefront,
    parseStorefront,
    parseStorefrontDetailed,
    STOREFRONT_META_VERSION,
    STOREFRONT_REQUIRED_KEYS,
} from '../storefront';

const expectRequiredArrays = (value: Record<string, unknown>) =>
    STOREFRONT_REQUIRED_KEYS.forEach(key => expect(Array.isArray(value[key])).toBe(true));

/** Small deterministic PRNG (mulberry32), so the fuzz corpus is the same on every run. */
function rng(seed: number) {
    let state = seed >>> 0;
    return () => {
        state = (state + 0x6d2b79f5) >>> 0;
        let t = state;
        t = Math.imul(t ^ (t >>> 15), t | 1);
        t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}

function randomValue(next: () => number, depth: number): unknown {
    const pick = Math.floor(next() * (depth > 3 ? 6 : 9));
    switch (pick) {
        case 0:
            return null;
        case 1:
            return undefined;
        case 2:
            return next() * 1000 - 500;
        case 3:
            return ['', 'tokentails', 'rozine-pedute', '__proto__', '💥'][Math.floor(next() * 5)];
        case 4:
            return next() > 0.5;
        case 5:
            return [NaN, Infinity, -0][Math.floor(next() * 3)];
        case 6:
        case 7: {
            const out: unknown[] = [];
            const n = Math.floor(next() * 5);
            for (let i = 0; i < n; i += 1) out.push(randomValue(next, depth + 1));
            return out;
        }
        default: {
            const out: Record<string, unknown> = {};
            const keys = [
                'tokentails',
                'token-tails',
                'token-tails-2',
                'rozine-pedute',
                '_meta',
                'x',
                'unknown',
                '_id',
                'shelters',
                '_v',
                'generatedAt',
                'slug',
                'name',
                'role',
            ];
            const n = Math.floor(next() * 6);
            for (let i = 0; i < n; i += 1) {
                out[keys[Math.floor(next() * keys.length)]] = randomValue(next, depth + 1);
            }
            return out;
        }
    }
}

describe('parseStorefront', () => {
    it('keeps a well-formed response as is and reads _meta', () => {
        const raw = {
            tokentails: [{ _id: 'a' }],
            'token-tails': [],
            'token-tails-2': [{ _id: 'b' }],
            'rozine-pedute': [{ _id: 'c' }],
            'new-shelter': [{ _id: 'd' }],
            _meta: {
                _v: STOREFRONT_META_VERSION,
                generatedAt: '2026-09-30T00:00:00.000Z',
                shelters: [
                    { slug: 'rozine-pedute', name: 'Rozine pedute', role: 'partner' },
                    { slug: 'token-tails-2', name: 'Token Tails', role: 'house' },
                ],
            },
        };
        const parsed = parseStorefrontDetailed(raw);
        expect(parsed.degraded).toBe(false);
        expect(parsed.cats).toEqual({
            tokentails: [{ _id: 'a' }],
            'token-tails': [],
            'token-tails-2': [{ _id: 'b' }],
            'rozine-pedute': [{ _id: 'c' }],
            'new-shelter': [{ _id: 'd' }],
        });
        expect(parsed.meta?.shelters.map(s => s.role)).toEqual(['partner', 'house']);
    });

    it('fills every missing required key with an array (the legacy shape that crashed ShelterScene)', () => {
        const cats = parseStorefront({ tokentails: [{ _id: 'a' }] });
        expectRequiredArrays(cats);
        expect(cats['token-tails-2']).toEqual([]);
        expect(cats.tokentails).toEqual([{ _id: 'a' }]);
    });

    it('flags a response missing a required key as degraded', () => {
        const parsed = parseStorefrontDetailed({ tokentails: [], 'token-tails': [], 'token-tails-2': [] });
        expect(parsed.degraded).toBe(true);
        expect(parsed.cats['rozine-pedute']).toEqual([]);
    });

    it('turns the old [] fallback, null and garbage into the empty storefront', () => {
        [[], null, undefined, 'oops', 42, true].forEach(raw => {
            const parsed = parseStorefrontDetailed(raw);
            expect(parsed.degraded).toBe(true);
            expect(parsed.cats).toEqual(emptyStorefront());
            expectRequiredArrays(parsed.cats);
        });
    });

    it('keeps extra keys, coerces non-array values to [] and drops non-object entries', () => {
        const parsed = parseStorefrontDetailed({ extra: 'nope', other: [null, 1, { _id: 'ok' }, 'x'] });
        expect(parsed.degraded).toBe(true);
        expect(parsed.cats.extra).toEqual([]);
        expect(parsed.cats.other).toEqual([{ _id: 'ok' }]);
    });

    it('ignores invalid _meta and invalid shelter entries', () => {
        expect(parseStorefrontDetailed({ _meta: 'x' }).meta).toBeNull();
        expect(parseStorefrontDetailed({ _meta: { _v: '1', generatedAt: 'now' } }).meta).toBeNull();
        const meta = parseStorefrontDetailed({
            _meta: {
                _v: 1,
                generatedAt: 'now',
                shelters: [
                    { slug: 'a', name: 'A', role: 'owner' },
                    { slug: '', name: 'B', role: 'house' },
                    null,
                    { slug: 'c', name: 'C', role: 'house' },
                ],
            },
        }).meta;
        expect(meta?.shelters).toEqual([{ slug: 'c', name: 'C', role: 'house' }]);
        expect(parseStorefront({ _meta: { _v: 1 } })).not.toHaveProperty('_meta');
    });

    it('does not let a __proto__ key pollute the result', () => {
        const raw = JSON.parse('{"__proto__": [{"polluted": true}], "tokentails": []}');
        const cats = parseStorefront(raw);
        expect(Object.getPrototypeOf(cats)).toBe(Object.prototype);
        expect(({} as Record<string, unknown>).polluted).toBeUndefined();
    });

    it('survives objects whose getters throw', () => {
        const hostile = {};
        Object.defineProperty(hostile, 'tokentails', {
            enumerable: true,
            get: () => {
                throw new Error('boom');
            },
        });
        const cats = parseStorefront(hostile);
        expect(cats.tokentails).toEqual([]);
    });

    it('never throws and always returns arrays on a 2000-case fuzz corpus', () => {
        const next = rng(20260930);
        for (let i = 0; i < 2000; i += 1) {
            const raw = randomValue(next, 0);
            let parsed: ReturnType<typeof parseStorefrontDetailed> | undefined;
            expect(() => {
                parsed = parseStorefrontDetailed(raw);
            }).not.toThrow();
            const cats = parsed!.cats as Record<string, unknown>;
            expectRequiredArrays(cats);
            Object.keys(cats).forEach(key => {
                expect(Array.isArray(cats[key])).toBe(true);
                (cats[key] as unknown[]).forEach(entry => expect(entry && typeof entry === 'object').toBeTruthy());
            });
            if (raw && typeof raw === 'object' && !Array.isArray(raw)) {
                Object.keys(raw)
                    .filter(key => key !== '_meta' && key !== '__proto__')
                    .forEach(key => {
                        expect(Object.prototype.hasOwnProperty.call(cats, key)).toBe(true);
                    });
            }
        }
    });
});
