export enum GameModal {
  QUESTS = "QUESTS",
  PROFILE = "PROFILE",
  LEADERBOARD = "LEADERBOARD",
}

export enum GameType {
  SHELTER = 'SHELTER',
  HOME = 'HOME',
  PURRQUEST = 'PURRQUEST',
  CATBASSADORS = 'CATBASSADORS',
}