export enum GameModal {
  QUESTS = "QUESTS",
  PROFILE = "PROFILE",
  LEADERBOARD = "LEADERBOARD",
  LEADERBOARD_DAILY = "LEADERBOARD_DAILY",
  CATS = "CATS",
}

export enum GameType {
  SHELTER = 'SHELTER',
  HOME = 'HOME',
  PURRQUEST = 'PURRQUEST',
  CATBASSADORS = 'CATBASSADORS',
}